package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:23 PM by Hibernate Tools 3.1.0.beta4



/**
 * Accountuserpladmin generated by hbm2java
 */

public class Accountuserpladmin  implements java.io.Serializable {


    // Fields    

     private int accountuserpladminid;
     private int accountuserid;
     private int plid;


    // Constructors

    /** default constructor */
    public Accountuserpladmin() {
    }

	/** minimal constructor */
    public Accountuserpladmin(int accountuserpladminid, int accountuserid) {
        this.accountuserpladminid = accountuserpladminid;
        this.accountuserid = accountuserid;
    }
    
    /** full constructor */
    public Accountuserpladmin(int accountuserpladminid, int accountuserid, Integer plid) {
        this.accountuserpladminid = accountuserpladminid;
        this.accountuserid = accountuserid;
        this.plid = plid;
    }
    

   
    // Property accessors

    public int getAccountuserpladminid() {
        return this.accountuserpladminid;
    }
    
    public void setAccountuserpladminid(int accountuserpladminid) {
        this.accountuserpladminid = accountuserpladminid;
    }

    public int getAccountuserid() {
        return this.accountuserid;
    }
    
    public void setAccountuserid(int accountuserid) {
        this.accountuserid = accountuserid;
    }

    public int getPlid() {
        return this.plid;
    }
    
    public void setPlid(int plid) {
        this.plid = plid;
    }
   








}
