package reger.dao.hibernate;
// Generated Mar 7, 2006 3:42:57 PM by Hibernate Tools 3.1.0.beta4



/**
 * Accountuseraclgroup generated by hbm2java
 */

public class Accountuseraclgroup  implements java.io.Serializable {


    // Fields    

     private int accountuseraclgroupid;
     private int accountuserid;
     private int aclgroupid;
     private int accountid;


    // Constructors

    /** default constructor */
    public Accountuseraclgroup() {
    }

    
    /** full constructor */
    public Accountuseraclgroup(int accountuseraclgroupid, int accountuserid, int aclgroupid, int accountid) {
        this.accountuseraclgroupid = accountuseraclgroupid;
        this.accountuserid = accountuserid;
        this.aclgroupid = aclgroupid;
        this.accountid = accountid;
    }
    

   
    // Property accessors

    public int getAccountuseraclgroupid() {
        return this.accountuseraclgroupid;
    }
    
    public void setAccountuseraclgroupid(int accountuseraclgroupid) {
        this.accountuseraclgroupid = accountuseraclgroupid;
    }

    public int getAccountuserid() {
        return this.accountuserid;
    }
    
    public void setAccountuserid(int accountuserid) {
        this.accountuserid = accountuserid;
    }

    public int getAclgroupid() {
        return this.aclgroupid;
    }
    
    public void setAclgroupid(int aclgroupid) {
        this.aclgroupid = aclgroupid;
    }

    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }
   








}
