package reger.dao.hibernate;
// Generated Mar 7, 2006 3:42:40 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.Set;
import java.util.HashSet;


/**
 * Accountuser generated by hbm2java
 */

public class Accountuser  implements java.io.Serializable {


    // Fields    

     private int accountuserid;
     private boolean isactive;
     private int accountid;
     private String password;
     private String username;
     private String friendlyname;
     private String onelinesummary;
     private String passphrasequestion;
     private String passphraseanswer;
     private String email;
     private Date lastlogindate;
     private int entrymode;
     private String usertimezoneid;
     private Date createdate;
     private boolean ishelpon;
     private boolean isactivatedbyemail;
     private String emailactivationkey;
     private Date emailactivationlastsent;
     private int profileimageid;

    //Association
    private Set<Accountuseracl> accountuseracls = new HashSet<Accountuseracl>();
    public Set<Accountuseracl> getAccountuseracls() {
        return accountuseracls;
    }
    public void setAccountuseracls(Set<Accountuseracl> accountuseracls) {
        this.accountuseracls = accountuseracls;
    }

    //Association
    private Set<Aclgroup> aclgroups = new HashSet<Aclgroup>();
    public Set<Aclgroup> getAclgroups() {
        return aclgroups;
    }
    public void setAclgroups(Set<Aclgroup> aclgroups) {
        this.aclgroups = aclgroups;
    }

    //Association
    private Set<Accountuserfield> accountuserfields = new HashSet<Accountuserfield>();
    public Set<Accountuserfield> getAccountuserfields() {
        return accountuserfields;
    }
    public void setAccountuserfields(Set<Accountuserfield> accountuserfields) {
        this.accountuserfields = accountuserfields;
    }

    //Association
    private Set<Accountuserlogaccess> accountuserlogaccesses = new HashSet<Accountuserlogaccess>();
    public Set<Accountuserlogaccess> getAccountuserlogaccesses() {
        return accountuserlogaccesses;
    }
    public void setAccountuserlogaccesses(Set<Accountuserlogaccess> accountuserlogaccesses) {
        this.accountuserlogaccesses = accountuserlogaccesses;
    }

    //Association
    private Set<Accountuserpersistentlogin> accountuserpersistentlogins = new HashSet<Accountuserpersistentlogin>();
    public Set<Accountuserpersistentlogin> getAccountuserpersistentlogins() {
        return accountuserpersistentlogins;
    }
    public void setAccountuserpersistentlogins(Set<Accountuserpersistentlogin> accountuserpersistentlogins) {
        this.accountuserpersistentlogins = accountuserpersistentlogins;
    }

    //Association
    private Set<Accountuserpladmin> accountuserpladmins = new HashSet<Accountuserpladmin>();
    public Set<Accountuserpladmin> getAccountuserpladmins() {
        return accountuserpladmins;
    }
    public void setAccountuserpladmins(Set<Accountuserpladmin> accountuserpladmins) {
        this.accountuserpladmins = accountuserpladmins;
    }

    //Association
    private Set<Accountuser> friends = new HashSet<Accountuser>();
    public Set<Accountuser> getFriends() {
        return friends;
    }
    public void setFriends(Set<Accountuser> friends) {
        this.friends = friends;
    }

    //Association
    private Set<Friendmessage> sentfriendmessages = new HashSet<Friendmessage>();
    public Set<Friendmessage> getSentfriendmessages() {
        return sentfriendmessages;
    }
    public void setSentfriendmessages(Set<Friendmessage> sentfriendmessages) {
        this.sentfriendmessages = sentfriendmessages;
    }

    //Association
    private Set<Friendmessage> receivedfriendmessages = new HashSet<Friendmessage>();
    public Set<Friendmessage> getReceivedfriendmessages() {
        return receivedfriendmessages;
    }
    public void setReceivedfriendmessages(Set<Friendmessage> receivedfriendmessages) {
        this.receivedfriendmessages = receivedfriendmessages;
    }

    // Constructors

    /** default constructor */
    public Accountuser() {
    }

    /** minimal constructor */
    public Accountuser(int accountuserid, int accountid, String password, String username, String passphrasequestion, String passphraseanswer, int entrymode, String usertimezoneid, Date createdate) {
        this.accountuserid = accountuserid;
        this.accountid = accountid;
        this.password = password;
        this.username = username;
        this.passphrasequestion = passphrasequestion;
        this.passphraseanswer = passphraseanswer;
        this.entrymode = entrymode;
        this.usertimezoneid = usertimezoneid;
        this.createdate = createdate;
    }

    /** full constructor */
    public Accountuser(int accountuserid, boolean isactive, int accountid, String password, String username, String friendlyname, String onelinesummary, String passphrasequestion, String passphraseanswer, String email, Date lastlogindate, int entrymode, String usertimezoneid, Date createdate, boolean ishelpon, boolean isactivatedbyemail, String emailactivationkey, Date emailactivationlastsent, Integer profileimageid) {
        this.accountuserid = accountuserid;
        this.isactive = isactive;
        this.accountid = accountid;
        this.password = password;
        this.username = username;
        this.friendlyname = friendlyname;
        this.onelinesummary = onelinesummary;
        this.passphrasequestion = passphrasequestion;
        this.passphraseanswer = passphraseanswer;
        this.email = email;
        this.lastlogindate = lastlogindate;
        this.entrymode = entrymode;
        this.usertimezoneid = usertimezoneid;
        this.createdate = createdate;
        this.ishelpon = ishelpon;
        this.isactivatedbyemail = isactivatedbyemail;
        this.emailactivationkey = emailactivationkey;
        this.emailactivationlastsent = emailactivationlastsent;
        this.profileimageid = profileimageid;
    }



    // Property accessors

    public int getAccountuserid() {
        return this.accountuserid;
    }

    public void setAccountuserid(int accountuserid) {
        this.accountuserid = accountuserid;
    }

    public boolean getIsactive() {
        return this.isactive;
    }

    public void setIsactive(boolean isactive) {
        this.isactive = isactive;
    }

    public int getAccountid() {
        return this.accountid;
    }

    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getFriendlyname() {
        return this.friendlyname;
    }

    public void setFriendlyname(String friendlyname) {
        this.friendlyname = friendlyname;
    }

    public String getOnelinesummary() {
        return this.onelinesummary;
    }

    public void setOnelinesummary(String onelinesummary) {
        this.onelinesummary = onelinesummary;
    }

    public String getPassphrasequestion() {
        return this.passphrasequestion;
    }

    public void setPassphrasequestion(String passphrasequestion) {
        this.passphrasequestion = passphrasequestion;
    }

    public String getPassphraseanswer() {
        return this.passphraseanswer;
    }

    public void setPassphraseanswer(String passphraseanswer) {
        this.passphraseanswer = passphraseanswer;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getLastlogindate() {
        return this.lastlogindate;
    }

    public void setLastlogindate(Date lastlogindate) {
        this.lastlogindate = lastlogindate;
    }

    public int getEntrymode() {
        return this.entrymode;
    }

    public void setEntrymode(int entrymode) {
        this.entrymode = entrymode;
    }

    public String getUsertimezoneid() {
        return this.usertimezoneid;
    }

    public void setUsertimezoneid(String usertimezoneid) {
        this.usertimezoneid = usertimezoneid;
    }

    public Date getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    public boolean getIshelpon() {
        return this.ishelpon;
    }

    public void setIshelpon(boolean ishelpon) {
        this.ishelpon = ishelpon;
    }

    public boolean getIsactivatedbyemail() {
        return this.isactivatedbyemail;
    }

    public void setIsactivatedbyemail(boolean isactivatedbyemail) {
        this.isactivatedbyemail = isactivatedbyemail;
    }

    public String getEmailactivationkey() {
        return this.emailactivationkey;
    }

    public void setEmailactivationkey(String emailactivationkey) {
        this.emailactivationkey = emailactivationkey;
    }

    public Date getEmailactivationlastsent() {
        return this.emailactivationlastsent;
    }

    public void setEmailactivationlastsent(Date emailactivationlastsent) {
        this.emailactivationlastsent = emailactivationlastsent;
    }

    public int getProfileimageid() {
        return this.profileimageid;
    }

    public void setProfileimageid(int profileimageid) {
        this.profileimageid = profileimageid;
    }









}
