package reger.dao.hibernate;
// Generated Mar 7, 2006 3:42:54 PM by Hibernate Tools 3.1.0.beta4



/**
 * Accountuserlogaccess generated by hbm2java
 */

public class Accountuserlogaccess  implements java.io.Serializable {


    // Fields    

     private int accountuserlogaccessid;
     private int accountuserid;
     private int logid;
     private boolean canread;
     private boolean canwrite;


    // Constructors

    /** default constructor */
    public Accountuserlogaccess() {
    }

	/** minimal constructor */
    public Accountuserlogaccess(int accountuserlogaccessid, int accountuserid, int logid) {
        this.accountuserlogaccessid = accountuserlogaccessid;
        this.accountuserid = accountuserid;
        this.logid = logid;
    }
    
    /** full constructor */
    public Accountuserlogaccess(int accountuserlogaccessid, int accountuserid, int logid, boolean canread, boolean canwrite) {
        this.accountuserlogaccessid = accountuserlogaccessid;
        this.accountuserid = accountuserid;
        this.logid = logid;
        this.canread = canread;
        this.canwrite = canwrite;
    }
    

   
    // Property accessors

    public int getAccountuserlogaccessid() {
        return this.accountuserlogaccessid;
    }
    
    public void setAccountuserlogaccessid(int accountuserlogaccessid) {
        this.accountuserlogaccessid = accountuserlogaccessid;
    }

    public int getAccountuserid() {
        return this.accountuserid;
    }
    
    public void setAccountuserid(int accountuserid) {
        this.accountuserid = accountuserid;
    }

    public int getLogid() {
        return this.logid;
    }
    
    public void setLogid(int logid) {
        this.logid = logid;
    }

    public boolean getCanread() {
        return this.canread;
    }
    
    public void setCanread(boolean canread) {
        this.canread = canread;
    }

    public boolean getCanwrite() {
        return this.canwrite;
    }
    
    public void setCanwrite(boolean canwrite) {
        this.canwrite = canwrite;
    }
   








}
