package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:15 PM by Hibernate Tools 3.1.0.beta4



/**
 * Aclgroup generated by hbm2java
 */

public class Aclgroup  implements java.io.Serializable {


    // Fields    

     private int aclgroupid;
     private String aclgroupname;


    // Constructors

    /** default constructor */
    public Aclgroup() {
    }

	/** minimal constructor */
    public Aclgroup(int aclgroupid) {
        this.aclgroupid = aclgroupid;
    }
    
    /** full constructor */
    public Aclgroup(int aclgroupid, String aclgroupname) {
        this.aclgroupid = aclgroupid;
        this.aclgroupname = aclgroupname;
    }
    

   
    // Property accessors

    public int getAclgroupid() {
        return this.aclgroupid;
    }
    
    public void setAclgroupid(int aclgroupid) {
        this.aclgroupid = aclgroupid;
    }

    public String getAclgroupname() {
        return this.aclgroupname;
    }
    
    public void setAclgroupname(String aclgroupname) {
        this.aclgroupname = aclgroupname;
    }
   








}
