package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:16 PM by Hibernate Tools 3.1.0.beta4



/**
 * Aclgroupmembershipgrants generated by hbm2java
 */

public class Aclgroupmembershipgrants  implements java.io.Serializable {


    // Fields    

     private int aclgroupmembershipgrantsid;
     private int aclgroupid;
     private int aclobjectid;


    // Constructors

    /** default constructor */
    public Aclgroupmembershipgrants() {
    }

    
    /** full constructor */
    public Aclgroupmembershipgrants(int aclgroupmembershipgrantsid, int aclgroupid, int aclobjectid) {
        this.aclgroupmembershipgrantsid = aclgroupmembershipgrantsid;
        this.aclgroupid = aclgroupid;
        this.aclobjectid = aclobjectid;
    }
    

   
    // Property accessors

    public int getAclgroupmembershipgrantsid() {
        return this.aclgroupmembershipgrantsid;
    }
    
    public void setAclgroupmembershipgrantsid(int aclgroupmembershipgrantsid) {
        this.aclgroupmembershipgrantsid = aclgroupmembershipgrantsid;
    }

    public int getAclgroupid() {
        return this.aclgroupid;
    }
    
    public void setAclgroupid(int aclgroupid) {
        this.aclgroupid = aclgroupid;
    }

    public int getAclobjectid() {
        return this.aclobjectid;
    }
    
    public void setAclobjectid(int aclobjectid) {
        this.aclobjectid = aclobjectid;
    }
   








}
