package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:26 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * Bug generated by hbm2java
 */

public class Bug  implements java.io.Serializable {


    // Fields    

     private int bugid;
     private Date createdate;
     private boolean isopen;
     private int severity;
     private int bugcategoryid;
     private String title;


    // Constructors

    /** default constructor */
    public Bug() {
    }

	/** minimal constructor */
    public Bug(int bugid) {
        this.bugid = bugid;
    }
    
    /** full constructor */
    public Bug(int bugid, Date createdate, boolean isopen, Integer severity, Integer bugcategoryid, String title) {
        this.bugid = bugid;
        this.createdate = createdate;
        this.isopen = isopen;
        this.severity = severity;
        this.bugcategoryid = bugcategoryid;
        this.title = title;
    }
    

   
    // Property accessors

    public int getBugid() {
        return this.bugid;
    }
    
    public void setBugid(int bugid) {
        this.bugid = bugid;
    }

    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    public boolean getIsopen() {
        return this.isopen;
    }
    
    public void setIsopen(boolean isopen) {
        this.isopen = isopen;
    }

    public int getSeverity() {
        return this.severity;
    }
    
    public void setSeverity(int severity) {
        this.severity = severity;
    }

    public int getBugcategoryid() {
        return this.bugcategoryid;
    }
    
    public void setBugcategoryid(int bugcategoryid) {
        this.bugcategoryid = bugcategoryid;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
   








}
