package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:10 PM by Hibernate Tools 3.1.0.beta4



/**
 * Bugcategory generated by hbm2java
 */

public class Bugcategory  implements java.io.Serializable {


    // Fields    

     private int bugcategoryid;
     private String bugcategory;


    // Constructors

    /** default constructor */
    public Bugcategory() {
    }

	/** minimal constructor */
    public Bugcategory(int bugcategoryid) {
        this.bugcategoryid = bugcategoryid;
    }
    
    /** full constructor */
    public Bugcategory(int bugcategoryid, String bugcategory) {
        this.bugcategoryid = bugcategoryid;
        this.bugcategory = bugcategory;
    }
    

   
    // Property accessors

    public int getBugcategoryid() {
        return this.bugcategoryid;
    }
    
    public void setBugcategoryid(int bugcategoryid) {
        this.bugcategoryid = bugcategoryid;
    }

    public String getBugcategory() {
        return this.bugcategory;
    }
    
    public void setBugcategory(String bugcategory) {
        this.bugcategory = bugcategory;
    }
   








}
