package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:26 PM by Hibernate Tools 3.1.0.beta4



/**
 * Cat generated by hbm2java
 */

public class Cat  implements java.io.Serializable {


    // Fields    

     private int catid;
     private String name;
     private Character sex;
     private Double weight;


    // Constructors

    /** default constructor */
    public Cat() {
    }

	/** minimal constructor */
    public Cat(int catid, String name) {
        this.catid = catid;
        this.name = name;
    }
    
    /** full constructor */
    public Cat(int catid, String name, Character sex, Double weight) {
        this.catid = catid;
        this.name = name;
        this.sex = sex;
        this.weight = weight;
    }
    

   
    // Property accessors

    public int getCatid() {
        return this.catid;
    }
    
    public void setCatid(int catid) {
        this.catid = catid;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Character getSex() {
        return this.sex;
    }
    
    public void setSex(Character sex) {
        this.sex = sex;
    }

    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }
   








}
