package reger.dao.hibernate;
// Generated Mar 7, 2006 3:42:42 PM by Hibernate Tools 3.1.0.beta4



/**
 * Contentpage generated by hbm2java
 */

public class Contentpage  implements java.io.Serializable {


    // Fields    

     private int contentpageid;
     private int accountid;
     private String name;
     private String content;
     private int nestednavparenttype;
     private int nestednavparentid;
     private int nestednavorder;
     private int sizeinbytes;


    // Constructors

    /** default constructor */
    public Contentpage() {
    }

	/** minimal constructor */
    public Contentpage(int contentpageid, int accountid, int nestednavparenttype, int nestednavparentid, int nestednavorder, int sizeinbytes) {
        this.contentpageid = contentpageid;
        this.accountid = accountid;
        this.nestednavparenttype = nestednavparenttype;
        this.nestednavparentid = nestednavparentid;
        this.nestednavorder = nestednavorder;
        this.sizeinbytes = sizeinbytes;
    }
    
    /** full constructor */
    public Contentpage(int contentpageid, int accountid, String name, String content, int nestednavparenttype, int nestednavparentid, int nestednavorder, int sizeinbytes) {
        this.contentpageid = contentpageid;
        this.accountid = accountid;
        this.name = name;
        this.content = content;
        this.nestednavparenttype = nestednavparenttype;
        this.nestednavparentid = nestednavparentid;
        this.nestednavorder = nestednavorder;
        this.sizeinbytes = sizeinbytes;
    }
    

   
    // Property accessors

    public int getContentpageid() {
        return this.contentpageid;
    }
    
    public void setContentpageid(int contentpageid) {
        this.contentpageid = contentpageid;
    }

    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public int getNestednavparenttype() {
        return this.nestednavparenttype;
    }
    
    public void setNestednavparenttype(int nestednavparenttype) {
        this.nestednavparenttype = nestednavparenttype;
    }

    public int getNestednavparentid() {
        return this.nestednavparentid;
    }
    
    public void setNestednavparentid(int nestednavparentid) {
        this.nestednavparentid = nestednavparentid;
    }

    public int getNestednavorder() {
        return this.nestednavorder;
    }
    
    public void setNestednavorder(int nestednavorder) {
        this.nestednavorder = nestednavorder;
    }

    public int getSizeinbytes() {
        return this.sizeinbytes;
    }
    
    public void setSizeinbytes(int sizeinbytes) {
        this.sizeinbytes = sizeinbytes;
    }
   








}
