package reger.dao.hibernate;

import java.util.Set;
import java.util.HashSet;
// Generated Mar 7, 2006 3:42:45 PM by Hibernate Tools 3.1.0.beta4



/**
 * Emailapi generated by hbm2java
 */

public class Emailapi  implements java.io.Serializable {


    // Fields    

     private int emailapiid;
     private int accountuserid;
     private String emailsecret;
     private boolean overridecamphonesubject;
     private String overridecamphonesubjecttext;
     private boolean ignorecamphonebody;
     private boolean consolidatecamphonetoonedailyentry;
     private boolean saveemailpostsasdraft;
     private boolean savecamphonepostsasdraft;
     private String camphoneimagetags;

    //Association
    private Set<Emailapiaddress> emailapiaddresses = new HashSet<Emailapiaddress>();
    public Set<Emailapiaddress> getEmailapiaddresses() {
        return emailapiaddresses;
    }
    public void setEmailapiaddresses(Set<Emailapiaddress> emailapiaddresses) {
        this.emailapiaddresses = emailapiaddresses;
    }

    // Constructors

    /** default constructor */
    public Emailapi() {
    }

	/** minimal constructor */
    public Emailapi(int emailapiid, int accountuserid) {
        this.emailapiid = emailapiid;
        this.accountuserid = accountuserid;
    }
    
    /** full constructor */
    public Emailapi(int emailapiid, int accountuserid, String emailsecret, boolean overridecamphonesubject, String overridecamphonesubjecttext, boolean ignorecamphonebody, boolean consolidatecamphonetoonedailyentry, boolean saveemailpostsasdraft, boolean savecamphonepostsasdraft, String camphoneimagetags) {
        this.emailapiid = emailapiid;
        this.accountuserid = accountuserid;
        this.emailsecret = emailsecret;
        this.overridecamphonesubject = overridecamphonesubject;
        this.overridecamphonesubjecttext = overridecamphonesubjecttext;
        this.ignorecamphonebody = ignorecamphonebody;
        this.consolidatecamphonetoonedailyentry = consolidatecamphonetoonedailyentry;
        this.saveemailpostsasdraft = saveemailpostsasdraft;
        this.savecamphonepostsasdraft = savecamphonepostsasdraft;
        this.camphoneimagetags = camphoneimagetags;
    }
    

   
    // Property accessors

    public int getEmailapiid() {
        return this.emailapiid;
    }
    
    public void setEmailapiid(int emailapiid) {
        this.emailapiid = emailapiid;
    }

    public int getAccountuserid() {
        return this.accountuserid;
    }
    
    public void setAccountuserid(int accountuserid) {
        this.accountuserid = accountuserid;
    }

    public String getEmailsecret() {
        return this.emailsecret;
    }
    
    public void setEmailsecret(String emailsecret) {
        this.emailsecret = emailsecret;
    }

    public boolean getOverridecamphonesubject() {
        return this.overridecamphonesubject;
    }
    
    public void setOverridecamphonesubject(boolean overridecamphonesubject) {
        this.overridecamphonesubject = overridecamphonesubject;
    }

    public String getOverridecamphonesubjecttext() {
        return this.overridecamphonesubjecttext;
    }
    
    public void setOverridecamphonesubjecttext(String overridecamphonesubjecttext) {
        this.overridecamphonesubjecttext = overridecamphonesubjecttext;
    }

    public boolean getIgnorecamphonebody() {
        return this.ignorecamphonebody;
    }
    
    public void setIgnorecamphonebody(boolean ignorecamphonebody) {
        this.ignorecamphonebody = ignorecamphonebody;
    }

    public boolean getConsolidatecamphonetoonedailyentry() {
        return this.consolidatecamphonetoonedailyentry;
    }
    
    public void setConsolidatecamphonetoonedailyentry(boolean consolidatecamphonetoonedailyentry) {
        this.consolidatecamphonetoonedailyentry = consolidatecamphonetoonedailyentry;
    }

    public boolean getSaveemailpostsasdraft() {
        return this.saveemailpostsasdraft;
    }
    
    public void setSaveemailpostsasdraft(boolean saveemailpostsasdraft) {
        this.saveemailpostsasdraft = saveemailpostsasdraft;
    }

    public boolean getSavecamphonepostsasdraft() {
        return this.savecamphonepostsasdraft;
    }
    
    public void setSavecamphonepostsasdraft(boolean savecamphonepostsasdraft) {
        this.savecamphonepostsasdraft = savecamphonepostsasdraft;
    }

    public String getCamphoneimagetags() {
        return this.camphoneimagetags;
    }
    
    public void setCamphoneimagetags(String camphoneimagetags) {
        this.camphoneimagetags = camphoneimagetags;
    }
   








}
