package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:15 PM by Hibernate Tools 3.1.0.beta4



/**
 * Eventxformdata generated by hbm2java
 */

public class Eventxformdata  implements java.io.Serializable {


    // Fields    

     private int eventxformdataid;
     private int eventid;
     private String xformdata;


    // Constructors

    /** default constructor */
    public Eventxformdata() {
    }

	/** minimal constructor */
    public Eventxformdata(int eventxformdataid) {
        this.eventxformdataid = eventxformdataid;
    }
    
    /** full constructor */
    public Eventxformdata(int eventxformdataid, Integer eventid, String xformdata) {
        this.eventxformdataid = eventxformdataid;
        this.eventid = eventid;
        this.xformdata = xformdata;
    }
    

   
    // Property accessors

    public int getEventxformdataid() {
        return this.eventxformdataid;
    }
    
    public void setEventxformdataid(int eventxformdataid) {
        this.eventxformdataid = eventxformdataid;
    }

    public int getEventid() {
        return this.eventid;
    }
    
    public void setEventid(int eventid) {
        this.eventid = eventid;
    }

    public String getXformdata() {
        return this.xformdata;
    }
    
    public void setXformdata(String xformdata) {
        this.xformdata = xformdata;
    }
   








}
