package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:24 PM by Hibernate Tools 3.1.0.beta4



/**
 * Eventtaglink generated by hbm2java
 */

public class Eventtaglink  implements java.io.Serializable {


    // Fields    

     private int eventtaglinkid;
     private int eventid;
     private int tagid;


    // Constructors

    /** default constructor */
    public Eventtaglink() {
    }

	/** minimal constructor */
    public Eventtaglink(int eventtaglinkid) {
        this.eventtaglinkid = eventtaglinkid;
    }
    
    /** full constructor */
    public Eventtaglink(int eventtaglinkid, Integer eventid, Integer tagid) {
        this.eventtaglinkid = eventtaglinkid;
        this.eventid = eventid;
        this.tagid = tagid;
    }
    

   
    // Property accessors

    public int getEventtaglinkid() {
        return this.eventtaglinkid;
    }
    
    public void setEventtaglinkid(int eventtaglinkid) {
        this.eventtaglinkid = eventtaglinkid;
    }

    public int getEventid() {
        return this.eventid;
    }
    
    public void setEventid(int eventid) {
        this.eventid = eventid;
    }

    public int getTagid() {
        return this.tagid;
    }
    
    public void setTagid(int tagid) {
        this.tagid = tagid;
    }
   








}
