package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:06 PM by Hibernate Tools 3.1.0.beta4



/**
 * Friendmessagerecipient generated by hbm2java
 */

public class Friendmessagerecipient  implements java.io.Serializable {


    // Fields    

     private int friendmessagerecipientid;
     private int friendmessageid;
     private int accountuserid;
     private boolean isread;


    // Constructors

    /** default constructor */
    public Friendmessagerecipient() {
    }

	/** minimal constructor */
    public Friendmessagerecipient(int friendmessagerecipientid, int friendmessageid, int accountuserid) {
        this.friendmessagerecipientid = friendmessagerecipientid;
        this.friendmessageid = friendmessageid;
        this.accountuserid = accountuserid;
    }
    
    /** full constructor */
    public Friendmessagerecipient(int friendmessagerecipientid, int friendmessageid, int accountuserid, boolean isread) {
        this.friendmessagerecipientid = friendmessagerecipientid;
        this.friendmessageid = friendmessageid;
        this.accountuserid = accountuserid;
        this.isread = isread;
    }
    

   
    // Property accessors

    public int getFriendmessagerecipientid() {
        return this.friendmessagerecipientid;
    }
    
    public void setFriendmessagerecipientid(int friendmessagerecipientid) {
        this.friendmessagerecipientid = friendmessagerecipientid;
    }

    public int getFriendmessageid() {
        return this.friendmessageid;
    }
    
    public void setFriendmessageid(int friendmessageid) {
        this.friendmessageid = friendmessageid;
    }

    public int getAccountuserid() {
        return this.accountuserid;
    }
    
    public void setAccountuserid(int accountuserid) {
        this.accountuserid = accountuserid;
    }

    public boolean getIsread() {
        return this.isread;
    }
    
    public void setIsread(boolean isread) {
        this.isread = isread;
    }
   








}
