package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:09 PM by Hibernate Tools 3.1.0.beta4



/**
 * Groupmembership generated by hbm2java
 */

public class Groupmembership  implements java.io.Serializable {


    // Fields    

     private int groupmembershipid;
     private int accountuserid;
     private int groupid;
     private boolean sharemembershippublicly;
     private boolean isapproved;
     private boolean ismoderator;


    // Constructors

    /** default constructor */
    public Groupmembership() {
    }

	/** minimal constructor */
    public Groupmembership(int groupmembershipid) {
        this.groupmembershipid = groupmembershipid;
    }
    
    /** full constructor */
    public Groupmembership(int groupmembershipid, Integer accountuserid, Integer groupid, boolean sharemembershippublicly, boolean isapproved, boolean ismoderator) {
        this.groupmembershipid = groupmembershipid;
        this.accountuserid = accountuserid;
        this.groupid = groupid;
        this.sharemembershippublicly = sharemembershippublicly;
        this.isapproved = isapproved;
        this.ismoderator = ismoderator;
    }
    

   
    // Property accessors

    public int getGroupmembershipid() {
        return this.groupmembershipid;
    }
    
    public void setGroupmembershipid(int groupmembershipid) {
        this.groupmembershipid = groupmembershipid;
    }

    public int getAccountuserid() {
        return this.accountuserid;
    }
    
    public void setAccountuserid(int accountuserid) {
        this.accountuserid = accountuserid;
    }

    public int getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(int groupid) {
        this.groupid = groupid;
    }

    public boolean getSharemembershippublicly() {
        return this.sharemembershippublicly;
    }
    
    public void setSharemembershippublicly(boolean sharemembershippublicly) {
        this.sharemembershippublicly = sharemembershippublicly;
    }

    public boolean getIsapproved() {
        return this.isapproved;
    }
    
    public void setIsapproved(boolean isapproved) {
        this.isapproved = isapproved;
    }

    public boolean getIsmoderator() {
        return this.ismoderator;
    }
    
    public void setIsmoderator(boolean ismoderator) {
        this.ismoderator = ismoderator;
    }
   








}
