package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:11 PM by Hibernate Tools 3.1.0.beta4



/**
 * Linkroteventlookup generated by hbm2java
 */

public class Linkroteventlookup  implements java.io.Serializable {


    // Fields    

     private int linkroteventlookupid;
     private int linkrotid;
     private int eventid;


    // Constructors

    /** default constructor */
    public Linkroteventlookup() {
    }

    
    /** full constructor */
    public Linkroteventlookup(int linkroteventlookupid, int linkrotid, int eventid) {
        this.linkroteventlookupid = linkroteventlookupid;
        this.linkrotid = linkrotid;
        this.eventid = eventid;
    }
    

   
    // Property accessors

    public int getLinkroteventlookupid() {
        return this.linkroteventlookupid;
    }
    
    public void setLinkroteventlookupid(int linkroteventlookupid) {
        this.linkroteventlookupid = linkroteventlookupid;
    }

    public int getLinkrotid() {
        return this.linkrotid;
    }
    
    public void setLinkrotid(int linkrotid) {
        this.linkrotid = linkrotid;
    }

    public int getEventid() {
        return this.eventid;
    }
    
    public void setEventid(int eventid) {
        this.eventid = eventid;
    }
   








}
