package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:07 PM by Hibernate Tools 3.1.0.beta4



/**
 * Locationtoevent generated by hbm2java
 */

public class Locationtoevent  implements java.io.Serializable {


    // Fields    

     private int locationtoeventid;
     private int locationid;
     private int eventid;


    // Constructors

    /** default constructor */
    public Locationtoevent() {
    }

	/** minimal constructor */
    public Locationtoevent(int locationtoeventid) {
        this.locationtoeventid = locationtoeventid;
    }
    
    /** full constructor */
    public Locationtoevent(int locationtoeventid, Integer locationid, Integer eventid) {
        this.locationtoeventid = locationtoeventid;
        this.locationid = locationid;
        this.eventid = eventid;
    }
    

   
    // Property accessors

    public int getLocationtoeventid() {
        return this.locationtoeventid;
    }
    
    public void setLocationtoeventid(int locationtoeventid) {
        this.locationtoeventid = locationtoeventid;
    }

    public int getLocationid() {
        return this.locationid;
    }
    
    public void setLocationid(int locationid) {
        this.locationid = locationid;
    }

    public int getEventid() {
        return this.eventid;
    }
    
    public void setEventid(int eventid) {
        this.eventid = eventid;
    }
   








}
