package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:14 PM by Hibernate Tools 3.1.0.beta4



/**
 * Logtypexform generated by hbm2java
 */

public class Logtypexform  implements java.io.Serializable {


    // Fields    

     private int logtypexformid;
     private int eventtypeid;
     private String xform;
     private String xformdefinition;


    // Constructors

    /** default constructor */
    public Logtypexform() {
    }

	/** minimal constructor */
    public Logtypexform(int logtypexformid) {
        this.logtypexformid = logtypexformid;
    }
    
    /** full constructor */
    public Logtypexform(int logtypexformid, Integer eventtypeid, String xform, String xformdefinition) {
        this.logtypexformid = logtypexformid;
        this.eventtypeid = eventtypeid;
        this.xform = xform;
        this.xformdefinition = xformdefinition;
    }
    

   
    // Property accessors

    public int getLogtypexformid() {
        return this.logtypexformid;
    }
    
    public void setLogtypexformid(int logtypexformid) {
        this.logtypexformid = logtypexformid;
    }

    public int getEventtypeid() {
        return this.eventtypeid;
    }
    
    public void setEventtypeid(int eventtypeid) {
        this.eventtypeid = eventtypeid;
    }

    public String getXform() {
        return this.xform;
    }
    
    public void setXform(String xform) {
        this.xform = xform;
    }

    public String getXformdefinition() {
        return this.xformdefinition;
    }
    
    public void setXformdefinition(String xformdefinition) {
        this.xformdefinition = xformdefinition;
    }
   








}
