package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:12 PM by Hibernate Tools 3.1.0.beta4



/**
 * Megadatatype generated by hbm2java
 */

public class Megadatatype  implements java.io.Serializable {


    // Fields    

     private int megadatatypeid;
     private String megadatatypename;
     private String megadatatypedescription;


    // Constructors

    /** default constructor */
    public Megadatatype() {
    }

	/** minimal constructor */
    public Megadatatype(int megadatatypeid) {
        this.megadatatypeid = megadatatypeid;
    }
    
    /** full constructor */
    public Megadatatype(int megadatatypeid, String megadatatypename, String megadatatypedescription) {
        this.megadatatypeid = megadatatypeid;
        this.megadatatypename = megadatatypename;
        this.megadatatypedescription = megadatatypedescription;
    }
    

   
    // Property accessors

    public int getMegadatatypeid() {
        return this.megadatatypeid;
    }
    
    public void setMegadatatypeid(int megadatatypeid) {
        this.megadatatypeid = megadatatypeid;
    }

    public String getMegadatatypename() {
        return this.megadatatypename;
    }
    
    public void setMegadatatypename(String megadatatypename) {
        this.megadatatypename = megadatatypename;
    }

    public String getMegadatatypedescription() {
        return this.megadatatypedescription;
    }
    
    public void setMegadatatypedescription(String megadatatypedescription) {
        this.megadatatypedescription = megadatatypedescription;
    }
   








}
