package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:05 PM by Hibernate Tools 3.1.0.beta4



/**
 * Megavalue generated by hbm2java
 */

public class Megavalue  implements java.io.Serializable {


    // Fields    

     private int megavalueid;
     private int megafieldid;
     private int eventid;
     private String megavalue;
     private String megavalueextended;


    // Constructors

    /** default constructor */
    public Megavalue() {
    }

	/** minimal constructor */
    public Megavalue(int megavalueid) {
        this.megavalueid = megavalueid;
    }
    
    /** full constructor */
    public Megavalue(int megavalueid, Integer megafieldid, Integer eventid, String megavalue, String megavalueextended) {
        this.megavalueid = megavalueid;
        this.megafieldid = megafieldid;
        this.eventid = eventid;
        this.megavalue = megavalue;
        this.megavalueextended = megavalueextended;
    }
    

   
    // Property accessors

    public int getMegavalueid() {
        return this.megavalueid;
    }
    
    public void setMegavalueid(int megavalueid) {
        this.megavalueid = megavalueid;
    }

    public int getMegafieldid() {
        return this.megafieldid;
    }
    
    public void setMegafieldid(int megafieldid) {
        this.megafieldid = megafieldid;
    }

    public int getEventid() {
        return this.eventid;
    }
    
    public void setEventid(int eventid) {
        this.eventid = eventid;
    }

    public String getMegavalue() {
        return this.megavalue;
    }
    
    public void setMegavalue(String megavalue) {
        this.megavalue = megavalue;
    }

    public String getMegavalueextended() {
        return this.megavalueextended;
    }
    
    public void setMegavalueextended(String megavalueextended) {
        this.megavalueextended = megavalueextended;
    }
   








}
