package reger.dao.hibernate;

import java.util.Set;
import java.util.HashSet;
// Generated Mar 7, 2006 3:42:58 PM by Hibernate Tools 3.1.0.beta4



/**
 * Megalogtype generated by hbm2java
 */

public class Megalogtype  implements java.io.Serializable {


    // Fields    

     private int eventtypeid;
     private String megalogname;
     private String description;
     private String longdescription;
     private boolean showlocation;
     private String icon;
     private boolean showonhomepage;
     private boolean issystemlogtype;
     private boolean isprivate;
     private int accountuserid;
     private String hiddenfields;
     private String fieldorder;


    //Association
    private Set<Megafield> megafields = new HashSet<Megafield>();
    public Set<Megafield> getMegafields() {
        return megafields;
    }
    public void setMegafields(Set<Megafield> megafields) {
        this.megafields = megafields;
    }

    //Association
    private Set<Logtypexform> logtypexforms = new HashSet<Logtypexform>();
    public Set<Logtypexform> getLogtypexforms() {
        return logtypexforms;
    }
    public void setLogtypexforms(Set<Logtypexform> logtypexforms) {
        this.logtypexforms = logtypexforms;
    }

    // Constructors

    /** default constructor */
    public Megalogtype() {
    }

	/** minimal constructor */
    public Megalogtype(int eventtypeid, int accountuserid) {
        this.eventtypeid = eventtypeid;
        this.accountuserid = accountuserid;
    }
    
    /** full constructor */
    public Megalogtype(int eventtypeid, String megalogname, String description, String longdescription, boolean showlocation, String icon, boolean showonhomepage, boolean issystemlogtype, boolean isprivate, int accountuserid, String hiddenfields, String fieldorder) {
        this.eventtypeid = eventtypeid;
        this.megalogname = megalogname;
        this.description = description;
        this.longdescription = longdescription;
        this.showlocation = showlocation;
        this.icon = icon;
        this.showonhomepage = showonhomepage;
        this.issystemlogtype = issystemlogtype;
        this.isprivate = isprivate;
        this.accountuserid = accountuserid;
        this.hiddenfields = hiddenfields;
        this.fieldorder = fieldorder;
    }
    

   
    // Property accessors

    public int getEventtypeid() {
        return this.eventtypeid;
    }
    
    public void setEventtypeid(int eventtypeid) {
        this.eventtypeid = eventtypeid;
    }

    public String getMegalogname() {
        return this.megalogname;
    }
    
    public void setMegalogname(String megalogname) {
        this.megalogname = megalogname;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getLongdescription() {
        return this.longdescription;
    }
    
    public void setLongdescription(String longdescription) {
        this.longdescription = longdescription;
    }

    public boolean getShowlocation() {
        return this.showlocation;
    }
    
    public void setShowlocation(boolean showlocation) {
        this.showlocation = showlocation;
    }

    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }

    public boolean getShowonhomepage() {
        return this.showonhomepage;
    }
    
    public void setShowonhomepage(boolean showonhomepage) {
        this.showonhomepage = showonhomepage;
    }

    public boolean getIssystemlogtype() {
        return this.issystemlogtype;
    }
    
    public void setIssystemlogtype(boolean issystemlogtype) {
        this.issystemlogtype = issystemlogtype;
    }

    public boolean getIsprivate() {
        return this.isprivate;
    }
    
    public void setIsprivate(boolean isprivate) {
        this.isprivate = isprivate;
    }

    public int getAccountuserid() {
        return this.accountuserid;
    }
    
    public void setAccountuserid(int accountuserid) {
        this.accountuserid = accountuserid;
    }

    public String getHiddenfields() {
        return this.hiddenfields;
    }
    
    public void setHiddenfields(String hiddenfields) {
        this.hiddenfields = hiddenfields;
    }

    public String getFieldorder() {
        return this.fieldorder;
    }
    
    public void setFieldorder(String fieldorder) {
        this.fieldorder = fieldorder;
    }
   








}
