package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:25 PM by Hibernate Tools 3.1.0.beta4



/**
 * Offensivecontentdefaults generated by hbm2java
 */

public class Offensivecontentdefaults  implements java.io.Serializable {


    // Fields    

     private int offensivecontentdefaultsid;
     private String content;


    // Constructors

    /** default constructor */
    public Offensivecontentdefaults() {
    }

	/** minimal constructor */
    public Offensivecontentdefaults(int offensivecontentdefaultsid) {
        this.offensivecontentdefaultsid = offensivecontentdefaultsid;
    }
    
    /** full constructor */
    public Offensivecontentdefaults(int offensivecontentdefaultsid, String content) {
        this.offensivecontentdefaultsid = offensivecontentdefaultsid;
        this.content = content;
    }
    

   
    // Property accessors

    public int getOffensivecontentdefaultsid() {
        return this.offensivecontentdefaultsid;
    }
    
    public void setOffensivecontentdefaultsid(int offensivecontentdefaultsid) {
        this.offensivecontentdefaultsid = offensivecontentdefaultsid;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
   








}
