package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:06 PM by Hibernate Tools 3.1.0.beta4



/**
 * Plcontentpage generated by hbm2java
 */

public class Plcontentpage  implements java.io.Serializable {


    // Fields    

     private int plcontentpageid;
     private int plid;
     private String name;
     private String content;
     private int nestednavparenttype;
     private int nestednavparentid;
     private int nestednavorder;


    // Constructors

    /** default constructor */
    public Plcontentpage() {
    }

	/** minimal constructor */
    public Plcontentpage(int plcontentpageid, int plid, int nestednavparenttype, int nestednavparentid, int nestednavorder) {
        this.plcontentpageid = plcontentpageid;
        this.plid = plid;
        this.nestednavparenttype = nestednavparenttype;
        this.nestednavparentid = nestednavparentid;
        this.nestednavorder = nestednavorder;
    }
    
    /** full constructor */
    public Plcontentpage(int plcontentpageid, int plid, String name, String content, int nestednavparenttype, int nestednavparentid, int nestednavorder) {
        this.plcontentpageid = plcontentpageid;
        this.plid = plid;
        this.name = name;
        this.content = content;
        this.nestednavparenttype = nestednavparenttype;
        this.nestednavparentid = nestednavparentid;
        this.nestednavorder = nestednavorder;
    }
    

   
    // Property accessors

    public int getPlcontentpageid() {
        return this.plcontentpageid;
    }
    
    public void setPlcontentpageid(int plcontentpageid) {
        this.plcontentpageid = plcontentpageid;
    }

    public int getPlid() {
        return this.plid;
    }
    
    public void setPlid(int plid) {
        this.plid = plid;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public int getNestednavparenttype() {
        return this.nestednavparenttype;
    }
    
    public void setNestednavparenttype(int nestednavparenttype) {
        this.nestednavparenttype = nestednavparenttype;
    }

    public int getNestednavparentid() {
        return this.nestednavparentid;
    }
    
    public void setNestednavparentid(int nestednavparentid) {
        this.nestednavparentid = nestednavparentid;
    }

    public int getNestednavorder() {
        return this.nestednavorder;
    }
    
    public void setNestednavorder(int nestednavorder) {
        this.nestednavorder = nestednavorder;
    }
   








}
