package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:14 PM by Hibernate Tools 3.1.0.beta4



/**
 * Pleventtypeid generated by hbm2java
 */

public class Pleventtypeid  implements java.io.Serializable {


    // Fields    

     private int pleventtypeid;
     private int plid;
     private int eventtypeid;
     private int priority;


    // Constructors

    /** default constructor */
    public Pleventtypeid() {
    }

	/** minimal constructor */
    public Pleventtypeid(int pleventtypeid) {
        this.pleventtypeid = pleventtypeid;
    }
    
    /** full constructor */
    public Pleventtypeid(int pleventtypeid, Integer plid, Integer eventtypeid, Integer priority) {
        this.pleventtypeid = pleventtypeid;
        this.plid = plid;
        this.eventtypeid = eventtypeid;
        this.priority = priority;
    }
    

   
    // Property accessors

    public int getPleventtypeid() {
        return this.pleventtypeid;
    }
    
    public void setPleventtypeid(int pleventtypeid) {
        this.pleventtypeid = pleventtypeid;
    }

    public int getPlid() {
        return this.plid;
    }
    
    public void setPlid(int plid) {
        this.plid = plid;
    }

    public int getEventtypeid() {
        return this.eventtypeid;
    }
    
    public void setEventtypeid(int eventtypeid) {
        this.eventtypeid = eventtypeid;
    }

    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }
   








}
