package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:02 PM by Hibernate Tools 3.1.0.beta4



/**
 * Plnavhide generated by hbm2java
 */

public class Plnavhide  implements java.io.Serializable {


    // Fields    

     private int plnavhideid;
     private int plid;
     private int nestednavid;


    // Constructors

    /** default constructor */
    public Plnavhide() {
    }

    
    /** full constructor */
    public Plnavhide(int plnavhideid, int plid, int nestednavid) {
        this.plnavhideid = plnavhideid;
        this.plid = plid;
        this.nestednavid = nestednavid;
    }
    

   
    // Property accessors

    public int getPlnavhideid() {
        return this.plnavhideid;
    }
    
    public void setPlnavhideid(int plnavhideid) {
        this.plnavhideid = plnavhideid;
    }

    public int getPlid() {
        return this.plid;
    }
    
    public void setPlid(int plid) {
        this.plid = plid;
    }

    public int getNestednavid() {
        return this.nestednavid;
    }
    
    public void setNestednavid(int nestednavid) {
        this.nestednavid = nestednavid;
    }
   








}
