package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:04 PM by Hibernate Tools 3.1.0.beta4



/**
 * Plpeer generated by hbm2java
 */

public class Plpeer  implements java.io.Serializable {


    // Fields    

     private int plpeerid;
     private int plid;
     private int peerplid;


    // Constructors

    /** default constructor */
    public Plpeer() {
    }

    
    /** full constructor */
    public Plpeer(int plpeerid, int plid, int peerplid) {
        this.plpeerid = plpeerid;
        this.plid = plid;
        this.peerplid = peerplid;
    }
    

   
    // Property accessors

    public int getPlpeerid() {
        return this.plpeerid;
    }
    
    public void setPlpeerid(int plpeerid) {
        this.plpeerid = plpeerid;
    }

    public int getPlid() {
        return this.plid;
    }
    
    public void setPlid(int plid) {
        this.plid = plid;
    }

    public int getPeerplid() {
        return this.peerplid;
    }
    
    public void setPeerplid(int peerplid) {
        this.peerplid = peerplid;
    }
   








}
