package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:05 PM by Hibernate Tools 3.1.0.beta4



/**
 * Pollanswer generated by hbm2java
 */

public class Pollanswer  implements java.io.Serializable {


    // Fields    

     private int pollanswerid;
     private int pollid;
     private String answer;
     private int votes;


    // Constructors

    /** default constructor */
    public Pollanswer() {
    }

	/** minimal constructor */
    public Pollanswer(int pollanswerid) {
        this.pollanswerid = pollanswerid;
    }
    
    /** full constructor */
    public Pollanswer(int pollanswerid, Integer pollid, String answer, Integer votes) {
        this.pollanswerid = pollanswerid;
        this.pollid = pollid;
        this.answer = answer;
        this.votes = votes;
    }
    

   
    // Property accessors

    public int getPollanswerid() {
        return this.pollanswerid;
    }
    
    public void setPollanswerid(int pollanswerid) {
        this.pollanswerid = pollanswerid;
    }

    public int getPollid() {
        return this.pollid;
    }
    
    public void setPollid(int pollid) {
        this.pollid = pollid;
    }

    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public int getVotes() {
        return this.votes;
    }
    
    public void setVotes(int votes) {
        this.votes = votes;
    }
   








}
