package reger.dao.hibernate;

import java.util.Set;
import java.util.HashSet;
// Generated Mar 7, 2006 3:42:38 PM by Hibernate Tools 3.1.0.beta4



/**
 * Poll generated by hbm2java
 */

public class Poll  implements java.io.Serializable {


    // Fields    

     private int pollid;
     private int eventid;
     private String question;
     private boolean readerscanaddownanswer;
     private boolean readerscanaddcomments;
     private boolean readerscanvoteonreaderanswers;
     private boolean readerinputismoderated;
     private boolean isopen;

     //Association
     private Set<Pollanswer> pollanswers = new HashSet<Pollanswer>();
     public Set<Pollanswer> getPollanswers() {
        return pollanswers;
     }
     public void setPollanswers(Set<Pollanswer> pollanswers) {
        this.pollanswers = pollanswers;
     }

     //Association
     private Set<Pollreaderanswer> pollreaderanswers = new HashSet<Pollreaderanswer>();
     public Set<Pollreaderanswer> getPollreaderanswers() {
        return pollreaderanswers;
     }
     public void setPollreaderanswers(Set<Pollreaderanswer> pollreaderanswers) {
        this.pollreaderanswers = pollreaderanswers;
     }

     //Association
     private Set<Pollreadercomment> pollreadercomments = new HashSet<Pollreadercomment>();
     public Set<Pollreadercomment> getPollreadercomments() {
        return pollreadercomments;
     }
     public void setPollreadercomments(Set<Pollreadercomment> pollreadercomments) {
        this.pollreadercomments = pollreadercomments;
     }

    // Constructors

    /** default constructor */
    public Poll() {
    }

	/** minimal constructor */
    public Poll(int pollid) {
        this.pollid = pollid;
    }
    
    /** full constructor */
    public Poll(int pollid, Integer eventid, String question, boolean readerscanaddownanswer, boolean readerscanaddcomments, boolean readerscanvoteonreaderanswers, boolean readerinputismoderated, boolean isopen) {
        this.pollid = pollid;
        this.eventid = eventid;
        this.question = question;
        this.readerscanaddownanswer = readerscanaddownanswer;
        this.readerscanaddcomments = readerscanaddcomments;
        this.readerscanvoteonreaderanswers = readerscanvoteonreaderanswers;
        this.readerinputismoderated = readerinputismoderated;
        this.isopen = isopen;
    }
    

   
    // Property accessors

    public int getPollid() {
        return this.pollid;
    }
    
    public void setPollid(int pollid) {
        this.pollid = pollid;
    }

    public int getEventid() {
        return this.eventid;
    }
    
    public void setEventid(int eventid) {
        this.eventid = eventid;
    }

    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }

    public boolean getReaderscanaddownanswer() {
        return this.readerscanaddownanswer;
    }
    
    public void setReaderscanaddownanswer(boolean readerscanaddownanswer) {
        this.readerscanaddownanswer = readerscanaddownanswer;
    }

    public boolean getReaderscanaddcomments() {
        return this.readerscanaddcomments;
    }
    
    public void setReaderscanaddcomments(boolean readerscanaddcomments) {
        this.readerscanaddcomments = readerscanaddcomments;
    }

    public boolean getReaderscanvoteonreaderanswers() {
        return this.readerscanvoteonreaderanswers;
    }
    
    public void setReaderscanvoteonreaderanswers(boolean readerscanvoteonreaderanswers) {
        this.readerscanvoteonreaderanswers = readerscanvoteonreaderanswers;
    }

    public boolean getReaderinputismoderated() {
        return this.readerinputismoderated;
    }
    
    public void setReaderinputismoderated(boolean readerinputismoderated) {
        this.readerinputismoderated = readerinputismoderated;
    }

    public boolean getIsopen() {
        return this.isopen;
    }
    
    public void setIsopen(boolean isopen) {
        this.isopen = isopen;
    }
   








}
