package reger.dao.hibernate;
// Generated Mar 7, 2006 3:42:50 PM by Hibernate Tools 3.1.0.beta4



/**
 * Pollreadercomment generated by hbm2java
 */

public class Pollreadercomment  implements java.io.Serializable {


    // Fields    

     private int pollreadercommentid;
     private int pollid;
     private String readername;
     private String comment;
     private boolean isapproved;


    // Constructors

    /** default constructor */
    public Pollreadercomment() {
    }

	/** minimal constructor */
    public Pollreadercomment(int pollreadercommentid) {
        this.pollreadercommentid = pollreadercommentid;
    }
    
    /** full constructor */
    public Pollreadercomment(int pollreadercommentid, Integer pollid, String readername, String comment, boolean isapproved) {
        this.pollreadercommentid = pollreadercommentid;
        this.pollid = pollid;
        this.readername = readername;
        this.comment = comment;
        this.isapproved = isapproved;
    }
    

   
    // Property accessors

    public int getPollreadercommentid() {
        return this.pollreadercommentid;
    }
    
    public void setPollreadercommentid(int pollreadercommentid) {
        this.pollreadercommentid = pollreadercommentid;
    }

    public int getPollid() {
        return this.pollid;
    }
    
    public void setPollid(int pollid) {
        this.pollid = pollid;
    }

    public String getReadername() {
        return this.readername;
    }
    
    public void setReadername(String readername) {
        this.readername = readername;
    }

    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    public boolean getIsapproved() {
        return this.isapproved;
    }
    
    public void setIsapproved(boolean isapproved) {
        this.isapproved = isapproved;
    }
   








}
