package reger.dao.hibernate;
// Generated Mar 7, 2006 3:42:57 PM by Hibernate Tools 3.1.0.beta4



/**
 * Pollreaderanswer generated by hbm2java
 */

public class Pollreaderanswer  implements java.io.Serializable {


    // Fields    

     private int pollreaderanswerid;
     private int pollid;
     private String answer;
     private String readername;
     private int votes;
     private boolean isapproved;


    // Constructors

    /** default constructor */
    public Pollreaderanswer() {
    }

	/** minimal constructor */
    public Pollreaderanswer(int pollreaderanswerid) {
        this.pollreaderanswerid = pollreaderanswerid;
    }
    
    /** full constructor */
    public Pollreaderanswer(int pollreaderanswerid, Integer pollid, String answer, String readername, Integer votes, boolean isapproved) {
        this.pollreaderanswerid = pollreaderanswerid;
        this.pollid = pollid;
        this.answer = answer;
        this.readername = readername;
        this.votes = votes;
        this.isapproved = isapproved;
    }
    

   
    // Property accessors

    public int getPollreaderanswerid() {
        return this.pollreaderanswerid;
    }
    
    public void setPollreaderanswerid(int pollreaderanswerid) {
        this.pollreaderanswerid = pollreaderanswerid;
    }

    public int getPollid() {
        return this.pollid;
    }
    
    public void setPollid(int pollid) {
        this.pollid = pollid;
    }

    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getReadername() {
        return this.readername;
    }
    
    public void setReadername(String readername) {
        this.readername = readername;
    }

    public int getVotes() {
        return this.votes;
    }
    
    public void setVotes(int votes) {
        this.votes = votes;
    }

    public boolean getIsapproved() {
        return this.isapproved;
    }
    
    public void setIsapproved(boolean isapproved) {
        this.isapproved = isapproved;
    }
   








}
