package reger.dao.hibernate;
// Generated Mar 7, 2006 3:42:55 PM by Hibernate Tools 3.1.0.beta4



/**
 * Savedsearchfqe generated by hbm2java
 */

public class Savedsearchfqe  implements java.io.Serializable {


    // Fields    

     private int savedsearchfqeid;
     private int megafieldid;
     private String paramname;
     private String paramvalue;
     private int savedsearchid;


    // Constructors

    /** default constructor */
    public Savedsearchfqe() {
    }

	/** minimal constructor */
    public Savedsearchfqe(int savedsearchfqeid) {
        this.savedsearchfqeid = savedsearchfqeid;
    }
    
    /** full constructor */
    public Savedsearchfqe(int savedsearchfqeid, Integer megafieldid, String paramname, String paramvalue, Integer savedsearchid) {
        this.savedsearchfqeid = savedsearchfqeid;
        this.megafieldid = megafieldid;
        this.paramname = paramname;
        this.paramvalue = paramvalue;
        this.savedsearchid = savedsearchid;
    }
    

   
    // Property accessors

    public int getSavedsearchfqeid() {
        return this.savedsearchfqeid;
    }
    
    public void setSavedsearchfqeid(int savedsearchfqeid) {
        this.savedsearchfqeid = savedsearchfqeid;
    }

    public int getMegafieldid() {
        return this.megafieldid;
    }
    
    public void setMegafieldid(int megafieldid) {
        this.megafieldid = megafieldid;
    }

    public String getParamname() {
        return this.paramname;
    }
    
    public void setParamname(String paramname) {
        this.paramname = paramname;
    }

    public String getParamvalue() {
        return this.paramvalue;
    }
    
    public void setParamvalue(String paramvalue) {
        this.paramvalue = paramvalue;
    }

    public int getSavedsearchid() {
        return this.savedsearchid;
    }
    
    public void setSavedsearchid(int savedsearchid) {
        this.savedsearchid = savedsearchid;
    }
   








}
