package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:22 PM by Hibernate Tools 3.1.0.beta4



/**
 * Savedsearchaccount generated by hbm2java
 */

public class Savedsearchaccount  implements java.io.Serializable {


    // Fields    

     private int savedsearchaccountid;
     private int savedsearchid;
     private int accountid;


    // Constructors

    /** default constructor */
    public Savedsearchaccount() {
    }

	/** minimal constructor */
    public Savedsearchaccount(int savedsearchaccountid) {
        this.savedsearchaccountid = savedsearchaccountid;
    }
    
    /** full constructor */
    public Savedsearchaccount(int savedsearchaccountid, Integer savedsearchid, Integer accountid) {
        this.savedsearchaccountid = savedsearchaccountid;
        this.savedsearchid = savedsearchid;
        this.accountid = accountid;
    }
    

   
    // Property accessors

    public int getSavedsearchaccountid() {
        return this.savedsearchaccountid;
    }
    
    public void setSavedsearchaccountid(int savedsearchaccountid) {
        this.savedsearchaccountid = savedsearchaccountid;
    }

    public int getSavedsearchid() {
        return this.savedsearchid;
    }
    
    public void setSavedsearchid(int savedsearchid) {
        this.savedsearchid = savedsearchid;
    }

    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }
   








}
