package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:04 PM by Hibernate Tools 3.1.0.beta4



/**
 * Savedsearchlocation generated by hbm2java
 */

public class Savedsearchlocation  implements java.io.Serializable {


    // Fields    

     private int savedsearchlocationid;
     private int savedsearchid;
     private int locationid;


    // Constructors

    /** default constructor */
    public Savedsearchlocation() {
    }

	/** minimal constructor */
    public Savedsearchlocation(int savedsearchlocationid) {
        this.savedsearchlocationid = savedsearchlocationid;
    }
    
    /** full constructor */
    public Savedsearchlocation(int savedsearchlocationid, Integer savedsearchid, Integer locationid) {
        this.savedsearchlocationid = savedsearchlocationid;
        this.savedsearchid = savedsearchid;
        this.locationid = locationid;
    }
    

   
    // Property accessors

    public int getSavedsearchlocationid() {
        return this.savedsearchlocationid;
    }
    
    public void setSavedsearchlocationid(int savedsearchlocationid) {
        this.savedsearchlocationid = savedsearchlocationid;
    }

    public int getSavedsearchid() {
        return this.savedsearchid;
    }
    
    public void setSavedsearchid(int savedsearchid) {
        this.savedsearchid = savedsearchid;
    }

    public int getLocationid() {
        return this.locationid;
    }
    
    public void setLocationid(int locationid) {
        this.locationid = locationid;
    }
   








}
