package reger.dao.hibernate;
// Generated Mar 7, 2006 3:42:52 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * Scheduler generated by hbm2java
 */

public class Scheduler  implements java.io.Serializable {


    // Fields    

     private int schedulerid;
     private int masterthreadid;
     private String task;
     private Date lastrun;
     private int timesrun;
     private String comment;


    // Constructors

    /** default constructor */
    public Scheduler() {
    }

	/** minimal constructor */
    public Scheduler(int schedulerid) {
        this.schedulerid = schedulerid;
    }
    
    /** full constructor */
    public Scheduler(int schedulerid, Integer masterthreadid, String task, Date lastrun, Integer timesrun, String comment) {
        this.schedulerid = schedulerid;
        this.masterthreadid = masterthreadid;
        this.task = task;
        this.lastrun = lastrun;
        this.timesrun = timesrun;
        this.comment = comment;
    }
    

   
    // Property accessors

    public int getSchedulerid() {
        return this.schedulerid;
    }
    
    public void setSchedulerid(int schedulerid) {
        this.schedulerid = schedulerid;
    }

    public int getMasterthreadid() {
        return this.masterthreadid;
    }
    
    public void setMasterthreadid(int masterthreadid) {
        this.masterthreadid = masterthreadid;
    }

    public String getTask() {
        return this.task;
    }
    
    public void setTask(String task) {
        this.task = task;
    }

    public Date getLastrun() {
        return this.lastrun;
    }
    
    public void setLastrun(Date lastrun) {
        this.lastrun = lastrun;
    }

    public int getTimesrun() {
        return this.timesrun;
    }
    
    public void setTimesrun(int timesrun) {
        this.timesrun = timesrun;
    }

    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
   








}
