package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:07 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * Timeperiod generated by hbm2java
 */

public class Timeperiod  implements java.io.Serializable {


    // Fields    

     private int timeperiodid;
     private int accountid;
     private Date startdate;
     private Date enddate;
     private String description;
     private boolean isprivate;
     private String title;
     private boolean isopenended;


    // Constructors

    /** default constructor */
    public Timeperiod() {
    }

	/** minimal constructor */
    public Timeperiod(int timeperiodid, int accountid) {
        this.timeperiodid = timeperiodid;
        this.accountid = accountid;
    }
    
    /** full constructor */
    public Timeperiod(int timeperiodid, int accountid, Date startdate, Date enddate, String description, boolean isprivate, String title, boolean isopenended) {
        this.timeperiodid = timeperiodid;
        this.accountid = accountid;
        this.startdate = startdate;
        this.enddate = enddate;
        this.description = description;
        this.isprivate = isprivate;
        this.title = title;
        this.isopenended = isopenended;
    }
    

   
    // Property accessors

    public int getTimeperiodid() {
        return this.timeperiodid;
    }
    
    public void setTimeperiodid(int timeperiodid) {
        this.timeperiodid = timeperiodid;
    }

    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }

    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public boolean getIsprivate() {
        return this.isprivate;
    }
    
    public void setIsprivate(boolean isprivate) {
        this.isprivate = isprivate;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public boolean getIsopenended() {
        return this.isopenended;
    }
    
    public void setIsopenended(boolean isopenended) {
        this.isopenended = isopenended;
    }
   








}
