package reger.dao.hibernate;
// Generated Mar 7, 2006 3:43:10 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * Trackback generated by hbm2java
 */

public class Trackback  implements java.io.Serializable {


    // Fields    

     private int trackbackid;
     private int eventid;
     private boolean isoutbound;
     private boolean ispingedalready;
     private String url;
     private String blogname;
     private String posttitle;
     private String excerpt;
     private Date datetime;
     private boolean isapproved;


    // Constructors

    /** default constructor */
    public Trackback() {
    }

	/** minimal constructor */
    public Trackback(int trackbackid, int eventid) {
        this.trackbackid = trackbackid;
        this.eventid = eventid;
    }
    
    /** full constructor */
    public Trackback(int trackbackid, int eventid, boolean isoutbound, boolean ispingedalready, String url, String blogname, String posttitle, String excerpt, Date datetime, boolean isapproved) {
        this.trackbackid = trackbackid;
        this.eventid = eventid;
        this.isoutbound = isoutbound;
        this.ispingedalready = ispingedalready;
        this.url = url;
        this.blogname = blogname;
        this.posttitle = posttitle;
        this.excerpt = excerpt;
        this.datetime = datetime;
        this.isapproved = isapproved;
    }
    

   
    // Property accessors

    public int getTrackbackid() {
        return this.trackbackid;
    }
    
    public void setTrackbackid(int trackbackid) {
        this.trackbackid = trackbackid;
    }

    public int getEventid() {
        return this.eventid;
    }
    
    public void setEventid(int eventid) {
        this.eventid = eventid;
    }

    public boolean getIsoutbound() {
        return this.isoutbound;
    }
    
    public void setIsoutbound(boolean isoutbound) {
        this.isoutbound = isoutbound;
    }

    public boolean getIspingedalready() {
        return this.ispingedalready;
    }
    
    public void setIspingedalready(boolean ispingedalready) {
        this.ispingedalready = ispingedalready;
    }

    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    public String getBlogname() {
        return this.blogname;
    }
    
    public void setBlogname(String blogname) {
        this.blogname = blogname;
    }

    public String getPosttitle() {
        return this.posttitle;
    }
    
    public void setPosttitle(String posttitle) {
        this.posttitle = posttitle;
    }

    public String getExcerpt() {
        return this.excerpt;
    }
    
    public void setExcerpt(String excerpt) {
        this.excerpt = excerpt;
    }

    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    public boolean getIsapproved() {
        return this.isapproved;
    }
    
    public void setIsapproved(boolean isapproved) {
        this.isapproved = isapproved;
    }
   








}
