package reger.dao.hibernate;
// Generated Mar 7, 2006 3:42:55 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * Vstransaction generated by hbm2java
 */

public class Vstransaction  implements java.io.Serializable {


    // Fields    

     private int vstransactionid;
     private int accountid;
     private Date datetime;
     private String vssentstring;
     private String vsresultstring;
     private String hostaddress;
     private String result;
     private String acct;
     private String amt;
     private String street;
     private String zip;
     private String rpref;
     private String profileid;


    // Constructors

    /** default constructor */
    public Vstransaction() {
    }

	/** minimal constructor */
    public Vstransaction(int vstransactionid) {
        this.vstransactionid = vstransactionid;
    }
    
    /** full constructor */
    public Vstransaction(int vstransactionid, Integer accountid, Date datetime, String vssentstring, String vsresultstring, String hostaddress, String result, String acct, String amt, String street, String zip, String rpref, String profileid) {
        this.vstransactionid = vstransactionid;
        this.accountid = accountid;
        this.datetime = datetime;
        this.vssentstring = vssentstring;
        this.vsresultstring = vsresultstring;
        this.hostaddress = hostaddress;
        this.result = result;
        this.acct = acct;
        this.amt = amt;
        this.street = street;
        this.zip = zip;
        this.rpref = rpref;
        this.profileid = profileid;
    }
    

   
    // Property accessors

    public int getVstransactionid() {
        return this.vstransactionid;
    }
    
    public void setVstransactionid(int vstransactionid) {
        this.vstransactionid = vstransactionid;
    }

    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }

    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    public String getVssentstring() {
        return this.vssentstring;
    }
    
    public void setVssentstring(String vssentstring) {
        this.vssentstring = vssentstring;
    }

    public String getVsresultstring() {
        return this.vsresultstring;
    }
    
    public void setVsresultstring(String vsresultstring) {
        this.vsresultstring = vsresultstring;
    }

    public String getHostaddress() {
        return this.hostaddress;
    }
    
    public void setHostaddress(String hostaddress) {
        this.hostaddress = hostaddress;
    }

    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }

    public String getAcct() {
        return this.acct;
    }
    
    public void setAcct(String acct) {
        this.acct = acct;
    }

    public String getAmt() {
        return this.amt;
    }
    
    public void setAmt(String amt) {
        this.amt = amt;
    }

    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getRpref() {
        return this.rpref;
    }
    
    public void setRpref(String rpref) {
        this.rpref = rpref;
    }

    public String getProfileid() {
        return this.profileid;
    }
    
    public void setProfileid(String profileid) {
        this.profileid = profileid;
    }
   








}
