package reger.dao;
// Generated Mar 7, 2006 3:42:48 PM by Hibernate Tools 3.1.0.beta4



/**
 * Accountuseracl generated by hbm2java
 */

public class Accountuseracl  implements java.io.Serializable {


    // Fields    

     private int accountuseraclid;
     private int accountuserid;
     private int aclobjectid;
     private int accountid;


    // Constructors

    /** default constructor */
    public Accountuseracl() {
    }

    
    /** full constructor */
    public Accountuseracl(int accountuseraclid, int accountuserid, int aclobjectid, int accountid) {
        this.accountuseraclid = accountuseraclid;
        this.accountuserid = accountuserid;
        this.aclobjectid = aclobjectid;
        this.accountid = accountid;
    }
    

   
    // Property accessors

    public int getAccountuseraclid() {
        return this.accountuseraclid;
    }
    
    public void setAccountuseraclid(int accountuseraclid) {
        this.accountuseraclid = accountuseraclid;
    }

    public int getAccountuserid() {
        return this.accountuserid;
    }
    
    public void setAccountuserid(int accountuserid) {
        this.accountuserid = accountuserid;
    }

    public int getAclobjectid() {
        return this.aclobjectid;
    }
    
    public void setAclobjectid(int aclobjectid) {
        this.aclobjectid = aclobjectid;
    }

    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }
   








}
