package reger.dao;
// Generated Mar 7, 2006 3:43:17 PM by Hibernate Tools 3.1.0.beta4



/**
 * Accountusertype generated by hbm2java
 */

public class Accountusertype  implements java.io.Serializable {


    // Fields    

     private int accountusertypeid;
     private String type;
     private String description;


    // Constructors

    /** default constructor */
    public Accountusertype() {
    }

    
    /** full constructor */
    public Accountusertype(int accountusertypeid, String type, String description) {
        this.accountusertypeid = accountusertypeid;
        this.type = type;
        this.description = description;
    }
    

   
    // Property accessors

    public int getAccountusertypeid() {
        return this.accountusertypeid;
    }
    
    public void setAccountusertypeid(int accountusertypeid) {
        this.accountusertypeid = accountusertypeid;
    }

    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
   








}
