package reger.dao;
// Generated Mar 7, 2006 3:42:53 PM by Hibernate Tools 3.1.0.beta4



/**
 * Accounttype generated by hbm2java
 */

public class Accounttype  implements java.io.Serializable {


    // Fields    

     private int accounttypeid;
     private String accounttypename;


    // Constructors

    /** default constructor */
    public Accounttype() {
    }

    
    /** full constructor */
    public Accounttype(int accounttypeid, String accounttypename) {
        this.accounttypeid = accounttypeid;
        this.accounttypename = accounttypename;
    }
    

   
    // Property accessors

    public int getAccounttypeid() {
        return this.accounttypeid;
    }
    
    public void setAccounttypeid(int accounttypeid) {
        this.accounttypeid = accounttypeid;
    }

    public String getAccounttypename() {
        return this.accounttypename;
    }
    
    public void setAccounttypename(String accounttypename) {
        this.accounttypename = accounttypename;
    }
   








}
