package reger.dao;
// Generated Mar 7, 2006 3:43:12 PM by Hibernate Tools 3.1.0.beta4



/**
 * Accountuserfield generated by hbm2java
 */

public class Accountuserfield  implements java.io.Serializable {


    // Fields    

     private int accountuserfieldid;
     private int accountuserid;
     private String fieldtitle;
     private String fielddata;
     private int order;


    // Constructors

    /** default constructor */
    public Accountuserfield() {
    }

	/** minimal constructor */
    public Accountuserfield(int accountuserfieldid, int accountuserid, int order) {
        this.accountuserfieldid = accountuserfieldid;
        this.accountuserid = accountuserid;
        this.order = order;
    }
    
    /** full constructor */
    public Accountuserfield(int accountuserfieldid, int accountuserid, String fieldtitle, String fielddata, int order) {
        this.accountuserfieldid = accountuserfieldid;
        this.accountuserid = accountuserid;
        this.fieldtitle = fieldtitle;
        this.fielddata = fielddata;
        this.order = order;
    }
    

   
    // Property accessors

    public int getAccountuserfieldid() {
        return this.accountuserfieldid;
    }
    
    public void setAccountuserfieldid(int accountuserfieldid) {
        this.accountuserfieldid = accountuserfieldid;
    }

    public int getAccountuserid() {
        return this.accountuserid;
    }
    
    public void setAccountuserid(int accountuserid) {
        this.accountuserid = accountuserid;
    }

    public String getFieldtitle() {
        return this.fieldtitle;
    }
    
    public void setFieldtitle(String fieldtitle) {
        this.fieldtitle = fieldtitle;
    }

    public String getFielddata() {
        return this.fielddata;
    }
    
    public void setFielddata(String fielddata) {
        this.fielddata = fielddata;
    }

    public int getOrder() {
        return this.order;
    }
    
    public void setOrder(int order) {
        this.order = order;
    }
   








}
