package reger.dao;
// Generated Mar 7, 2006 3:43:24 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * Accountuserpersistentlogin generated by hbm2java
 */

public class Accountuserpersistentlogin  implements java.io.Serializable {


    // Fields    

     private int accountuserpersistentloginid;
     private int accountuserid;
     private String randomstring;
     private Date lastusedtologin;


    // Constructors

    /** default constructor */
    public Accountuserpersistentlogin() {
    }

	/** minimal constructor */
    public Accountuserpersistentlogin(int accountuserpersistentloginid, int accountuserid, String randomstring) {
        this.accountuserpersistentloginid = accountuserpersistentloginid;
        this.accountuserid = accountuserid;
        this.randomstring = randomstring;
    }
    
    /** full constructor */
    public Accountuserpersistentlogin(int accountuserpersistentloginid, int accountuserid, String randomstring, Date lastusedtologin) {
        this.accountuserpersistentloginid = accountuserpersistentloginid;
        this.accountuserid = accountuserid;
        this.randomstring = randomstring;
        this.lastusedtologin = lastusedtologin;
    }
    

   
    // Property accessors

    public int getAccountuserpersistentloginid() {
        return this.accountuserpersistentloginid;
    }
    
    public void setAccountuserpersistentloginid(int accountuserpersistentloginid) {
        this.accountuserpersistentloginid = accountuserpersistentloginid;
    }

    public int getAccountuserid() {
        return this.accountuserid;
    }
    
    public void setAccountuserid(int accountuserid) {
        this.accountuserid = accountuserid;
    }

    public String getRandomstring() {
        return this.randomstring;
    }
    
    public void setRandomstring(String randomstring) {
        this.randomstring = randomstring;
    }

    public Date getLastusedtologin() {
        return this.lastusedtologin;
    }
    
    public void setLastusedtologin(Date lastusedtologin) {
        this.lastusedtologin = lastusedtologin;
    }
   








}
