package reger.dao;
// Generated Mar 7, 2006 3:42:51 PM by Hibernate Tools 3.1.0.beta4



/**
 * Aclobject generated by hbm2java
 */

public class Aclobject  implements java.io.Serializable {


    // Fields    

     private int aclobjectid;
     private String aclobjectname;
     private String aclfriendlyname;
     private String acldesc;


    // Constructors

    /** default constructor */
    public Aclobject() {
    }

    
    /** full constructor */
    public Aclobject(int aclobjectid, String aclobjectname, String aclfriendlyname, String acldesc) {
        this.aclobjectid = aclobjectid;
        this.aclobjectname = aclobjectname;
        this.aclfriendlyname = aclfriendlyname;
        this.acldesc = acldesc;
    }
    

   
    // Property accessors

    public int getAclobjectid() {
        return this.aclobjectid;
    }
    
    public void setAclobjectid(int aclobjectid) {
        this.aclobjectid = aclobjectid;
    }

    public String getAclobjectname() {
        return this.aclobjectname;
    }
    
    public void setAclobjectname(String aclobjectname) {
        this.aclobjectname = aclobjectname;
    }

    public String getAclfriendlyname() {
        return this.aclfriendlyname;
    }
    
    public void setAclfriendlyname(String aclfriendlyname) {
        this.aclfriendlyname = aclfriendlyname;
    }

    public String getAcldesc() {
        return this.acldesc;
    }
    
    public void setAcldesc(String acldesc) {
        this.acldesc = acldesc;
    }
   








}
