package reger.dao;
// Generated Mar 7, 2006 3:43:13 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * Databaseversion generated by hbm2java
 */

public class Databaseversion  implements java.io.Serializable {


    // Fields    

     private int databaseversionid;
     private int version;
     private Date date;


    // Constructors

    /** default constructor */
    public Databaseversion() {
    }

	/** minimal constructor */
    public Databaseversion(int databaseversionid) {
        this.databaseversionid = databaseversionid;
    }
    
    /** full constructor */
    public Databaseversion(int databaseversionid, Date date) {
        this.databaseversionid = databaseversionid;
        this.date = date;
    }
    

   
    // Property accessors

    public int getDatabaseversionid() {
        return this.databaseversionid;
    }
    
    public void setDatabaseversionid(int databaseversionid) {
        this.databaseversionid = databaseversionid;
    }

    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }

    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
   








}
