package reger.dao;
// Generated Mar 7, 2006 3:43:23 PM by Hibernate Tools 3.1.0.beta4



/**
 * Debuglevel generated by hbm2java
 */

public class Debuglevel  implements java.io.Serializable {


    // Fields
     private int debuglevelid;
     private int debuglevel;


    // Constructors

    /** default constructor */
    public Debuglevel() {
    }

    
    /** full constructor */
    public Debuglevel(int debuglevelid, int debuglevel) {
        this.debuglevelid = debuglevelid;
        this.debuglevel = debuglevel;
    }
    

   
    // Property accessors

    public int getDebuglevelid() {
        return this.debuglevelid;
    }
    
    public void setDebuglevelid(int debuglevelid) {
        this.debuglevelid = debuglevelid;
    }

    public int getDebuglevel() {
        return this.debuglevel;
    }
    
    public void setDebuglevel(int debuglevel) {
        this.debuglevel = debuglevel;
    }
   








}
