package reger.dao;
// Generated Mar 7, 2006 3:42:56 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * Emailsubscriber generated by hbm2java
 */

public class Emailsubscriber  implements java.io.Serializable {


    // Fields    

     private int emailsubscriberid;
     private int sendeveryxdays;
     private String emailaddress;
     private int accountid;
     private boolean htmlemail;
     private Date lastsentdate;


    // Constructors

    /** default constructor */
    public Emailsubscriber() {
    }

	/** minimal constructor */
    public Emailsubscriber(int emailsubscriberid, int sendeveryxdays, String emailaddress, int accountid) {
        this.emailsubscriberid = emailsubscriberid;
        this.sendeveryxdays = sendeveryxdays;
        this.emailaddress = emailaddress;
        this.accountid = accountid;
    }
    
    /** full constructor */
    public Emailsubscriber(int emailsubscriberid, int sendeveryxdays, String emailaddress, int accountid, boolean htmlemail, Date lastsentdate) {
        this.emailsubscriberid = emailsubscriberid;
        this.sendeveryxdays = sendeveryxdays;
        this.emailaddress = emailaddress;
        this.accountid = accountid;
        this.htmlemail = htmlemail;
        this.lastsentdate = lastsentdate;
    }
    

   
    // Property accessors

    public int getEmailsubscriberid() {
        return this.emailsubscriberid;
    }
    
    public void setEmailsubscriberid(int emailsubscriberid) {
        this.emailsubscriberid = emailsubscriberid;
    }

    public int getSendeveryxdays() {
        return this.sendeveryxdays;
    }
    
    public void setSendeveryxdays(int sendeveryxdays) {
        this.sendeveryxdays = sendeveryxdays;
    }

    public String getEmailaddress() {
        return this.emailaddress;
    }
    
    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress;
    }

    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }

    public boolean getHtmlemail() {
        return this.htmlemail;
    }
    
    public void setHtmlemail(boolean htmlemail) {
        this.htmlemail = htmlemail;
    }

    public Date getLastsentdate() {
        return this.lastsentdate;
    }
    
    public void setLastsentdate(Date lastsentdate) {
        this.lastsentdate = lastsentdate;
    }
   








}
