package reger.dao;
// Generated Mar 7, 2006 3:42:48 PM by Hibernate Tools 3.1.0.beta4



/**
 * Emailapiaddress generated by hbm2java
 */

public class Emailapiaddress  implements java.io.Serializable {


    // Fields    

     private int emailapiaddressid;
     private String uniquekey;
     private int accountuserid;
     private int accountid;
     private int logid;
     private int emailtype;


    // Constructors

    /** default constructor */
    public Emailapiaddress() {
    }

	/** minimal constructor */
    public Emailapiaddress(int emailapiaddressid) {
        this.emailapiaddressid = emailapiaddressid;
    }
    
    /** full constructor */
    public Emailapiaddress(int emailapiaddressid, String uniquekey, Integer accountuserid, Integer accountid, Integer logid, Integer emailtype) {
        this.emailapiaddressid = emailapiaddressid;
        this.uniquekey = uniquekey;
        this.accountuserid = accountuserid;
        this.accountid = accountid;
        this.logid = logid;
        this.emailtype = emailtype;
    }
    

   
    // Property accessors

    public int getEmailapiaddressid() {
        return this.emailapiaddressid;
    }
    
    public void setEmailapiaddressid(int emailapiaddressid) {
        this.emailapiaddressid = emailapiaddressid;
    }

    public String getUniquekey() {
        return this.uniquekey;
    }
    
    public void setUniquekey(String uniquekey) {
        this.uniquekey = uniquekey;
    }

    public int getAccountuserid() {
        return this.accountuserid;
    }
    
    public void setAccountuserid(int accountuserid) {
        this.accountuserid = accountuserid;
    }

    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }

    public int getLogid() {
        return this.logid;
    }
    
    public void setLogid(int logid) {
        this.logid = logid;
    }

    public int getEmailtype() {
        return this.emailtype;
    }
    
    public void setEmailtype(int emailtype) {
        this.emailtype = emailtype;
    }
   








}
