package reger.dao;
// Generated Mar 7, 2006 3:43:06 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * Error generated by hbm2java
 */

public class Error  implements java.io.Serializable {


    // Fields    

     private int errorid;
     private Date date;
     private String url;
     private String description;
     private String status;
     private int accountid;
     private int count;
     private String label;


    // Constructors

    /** default constructor */
    public Error() {
    }

	/** minimal constructor */
    public Error(int errorid, int count) {
        this.errorid = errorid;
        this.count = count;
    }
    
    /** full constructor */
    public Error(int errorid, Date date, String url, String description, String status, Integer accountid, int count, String label) {
        this.errorid = errorid;
        this.date = date;
        this.url = url;
        this.description = description;
        this.status = status;
        this.accountid = accountid;
        this.count = count;
        this.label = label;
    }
    

   
    // Property accessors

    public int getErrorid() {
        return this.errorid;
    }
    
    public void setErrorid(int errorid) {
        this.errorid = errorid;
    }

    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }

    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }

    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
   








}
