package reger.dao;
// Generated Mar 7, 2006 3:43:08 PM by Hibernate Tools 3.1.0.beta4



/**
 * Eventtogroup generated by hbm2java
 */

public class Eventtogroup  implements java.io.Serializable {


    // Fields    

     private int eventtogroupid;
     private int eventid;
     private int groupid;


    // Constructors

    /** default constructor */
    public Eventtogroup() {
    }

	/** minimal constructor */
    public Eventtogroup(int eventtogroupid) {
        this.eventtogroupid = eventtogroupid;
    }
    
    /** full constructor */
    public Eventtogroup(int eventtogroupid, Integer eventid, Integer groupid) {
        this.eventtogroupid = eventtogroupid;
        this.eventid = eventid;
        this.groupid = groupid;
    }
    

   
    // Property accessors

    public int getEventtogroupid() {
        return this.eventtogroupid;
    }
    
    public void setEventtogroupid(int eventtogroupid) {
        this.eventtogroupid = eventtogroupid;
    }

    public int getEventid() {
        return this.eventid;
    }
    
    public void setEventid(int eventid) {
        this.eventid = eventid;
    }

    public int getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(int groupid) {
        this.groupid = groupid;
    }
   








}
