package reger.dao;
// Generated Mar 7, 2006 3:42:49 PM by Hibernate Tools 3.1.0.beta4



/**
 * Eventtoepisode generated by hbm2java
 */

public class Eventtoepisode  implements java.io.Serializable {


    // Fields    

     private int eventtoepisodeid;
     private int eventid;
     private int episodeid;


    // Constructors

    /** default constructor */
    public Eventtoepisode() {
    }

	/** minimal constructor */
    public Eventtoepisode(int eventtoepisodeid) {
        this.eventtoepisodeid = eventtoepisodeid;
    }
    
    /** full constructor */
    public Eventtoepisode(int eventtoepisodeid, Integer eventid, Integer episodeid) {
        this.eventtoepisodeid = eventtoepisodeid;
        this.eventid = eventid;
        this.episodeid = episodeid;
    }
    

   
    // Property accessors

    public int getEventtoepisodeid() {
        return this.eventtoepisodeid;
    }
    
    public void setEventtoepisodeid(int eventtoepisodeid) {
        this.eventtoepisodeid = eventtoepisodeid;
    }

    public int getEventid() {
        return this.eventid;
    }
    
    public void setEventid(int eventid) {
        this.eventid = eventid;
    }

    public int getEpisodeid() {
        return this.episodeid;
    }
    
    public void setEpisodeid(int episodeid) {
        this.episodeid = episodeid;
    }
   








}
