package reger.dao;
// Generated Mar 7, 2006 3:42:47 PM by Hibernate Tools 3.1.0.beta4



/**
 * Fileacl generated by hbm2java
 */

public class Fileacl  implements java.io.Serializable {


    // Fields    

     private int fileaclid;
     private int accountid;
     private int accountuserid;
     private String pathandorfilename;


    // Constructors

    /** default constructor */
    public Fileacl() {
    }

	/** minimal constructor */
    public Fileacl(int fileaclid) {
        this.fileaclid = fileaclid;
    }
    
    /** full constructor */
    public Fileacl(int fileaclid, Integer accountid, Integer accountuserid, String pathandorfilename) {
        this.fileaclid = fileaclid;
        this.accountid = accountid;
        this.accountuserid = accountuserid;
        this.pathandorfilename = pathandorfilename;
    }
    

   
    // Property accessors

    public int getFileaclid() {
        return this.fileaclid;
    }
    
    public void setFileaclid(int fileaclid) {
        this.fileaclid = fileaclid;
    }

    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }

    public int getAccountuserid() {
        return this.accountuserid;
    }
    
    public void setAccountuserid(int accountuserid) {
        this.accountuserid = accountuserid;
    }

    public String getPathandorfilename() {
        return this.pathandorfilename;
    }
    
    public void setPathandorfilename(String pathandorfilename) {
        this.pathandorfilename = pathandorfilename;
    }
   








}
