package reger.dao;
// Generated Mar 7, 2006 3:43:22 PM by Hibernate Tools 3.1.0.beta4



/**
 * Friendinvitationeventtypeid generated by hbm2java
 */

public class Friendinvitationeventtypeid  implements java.io.Serializable {


    // Fields    

     private int friendinvitationeventtypeidid;
     private int friendinvitationid;
     private int eventtypeid;


    // Constructors

    /** default constructor */
    public Friendinvitationeventtypeid() {
    }

    
    /** full constructor */
    public Friendinvitationeventtypeid(int friendinvitationeventtypeidid, int friendinvitationid, int eventtypeid) {
        this.friendinvitationeventtypeidid = friendinvitationeventtypeidid;
        this.friendinvitationid = friendinvitationid;
        this.eventtypeid = eventtypeid;
    }
    

   
    // Property accessors

    public int getFriendinvitationeventtypeidid() {
        return this.friendinvitationeventtypeidid;
    }
    
    public void setFriendinvitationeventtypeidid(int friendinvitationeventtypeidid) {
        this.friendinvitationeventtypeidid = friendinvitationeventtypeidid;
    }

    public int getFriendinvitationid() {
        return this.friendinvitationid;
    }
    
    public void setFriendinvitationid(int friendinvitationid) {
        this.friendinvitationid = friendinvitationid;
    }

    public int getEventtypeid() {
        return this.eventtypeid;
    }
    
    public void setEventtypeid(int eventtypeid) {
        this.eventtypeid = eventtypeid;
    }
   








}
