package reger.dao;
// Generated Mar 7, 2006 3:42:58 PM by Hibernate Tools 3.1.0.beta4



/**
 * Friend generated by hbm2java
 */

public class Friend  implements java.io.Serializable {


    // Fields    

     private int friendid;
     private int accountuseridsource;
     private int accountuseridtarget;


    // Constructors

    /** default constructor */
    public Friend() {
    }

    
    /** full constructor */
    public Friend(int friendid, int accountuseridsource, int accountuseridtarget) {
        this.friendid = friendid;
        this.accountuseridsource = accountuseridsource;
        this.accountuseridtarget = accountuseridtarget;
    }
    

   
    // Property accessors

    public int getFriendid() {
        return this.friendid;
    }
    
    public void setFriendid(int friendid) {
        this.friendid = friendid;
    }

    public int getAccountuseridsource() {
        return this.accountuseridsource;
    }
    
    public void setAccountuseridsource(int accountuseridsource) {
        this.accountuseridsource = accountuseridsource;
    }

    public int getAccountuseridtarget() {
        return this.accountuseridtarget;
    }
    
    public void setAccountuseridtarget(int accountuseridtarget) {
        this.accountuseridtarget = accountuseridtarget;
    }
   








}
