package reger.dao;
// Generated Mar 7, 2006 3:43:13 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.Set;
import java.util.HashSet;


/**
 * Friendinvitation generated by hbm2java
 */

public class Friendinvitation  implements java.io.Serializable {


    // Fields    

     private int friendinvitationid;
     private int accountuseridsource;
     private int accountuseridtarget;
     private int status;
     private String email;
     private String subject;
     private String message;
     private Date createdate;
     private Date emaillastsentdate;
     private String friendinvitationkey;


    //Association
    private Set<Friendinvitationeventtypeid> friendinvitationeventtypeids = new HashSet<Friendinvitationeventtypeid>();
    public Set<Friendinvitationeventtypeid> getFriendinvitationeventtypeids() {
        return friendinvitationeventtypeids;
    }
    public void setFriendinvitationeventtypeids(Set<Friendinvitationeventtypeid> friendinvitationeventtypeids) {
        this.friendinvitationeventtypeids = friendinvitationeventtypeids;
    }

    //Association
    private Set<Friendinvitationgroup> friendinvitationgroups = new HashSet<Friendinvitationgroup>();
    public Set<Friendinvitationgroup> getFriendinvitationgroups() {
        return friendinvitationgroups;
    }
    public void setFriendinvitationgroups(Set<Friendinvitationgroup> friendinvitationgroups) {
        this.friendinvitationgroups = friendinvitationgroups;
    }

    //Association
    private Set<Friendinvitationlogid> friendinvitationlogids = new HashSet<Friendinvitationlogid>();
    public Set<Friendinvitationlogid> getFriendinvitationlogids() {
        return friendinvitationlogids;
    }
    public void setFriendinvitationlogids(Set<Friendinvitationlogid> friendinvitationlogids) {
        this.friendinvitationlogids = friendinvitationlogids;
    }

    // Constructors

    /** default constructor */
    public Friendinvitation() {
    }

    /** minimal constructor */
    public Friendinvitation(int friendinvitationid, int accountuseridsource, int status, String email, String subject, Date createdate) {
        this.friendinvitationid = friendinvitationid;
        this.accountuseridsource = accountuseridsource;
        this.status = status;
        this.email = email;
        this.subject = subject;
        this.createdate = createdate;
    }

    /** full constructor */
    public Friendinvitation(int friendinvitationid, int accountuseridsource, Integer accountuseridtarget, int status, String email, String subject, String message, Date createdate, Date emaillastsentdate, String friendinvitationkey) {
        this.friendinvitationid = friendinvitationid;
        this.accountuseridsource = accountuseridsource;
        this.accountuseridtarget = accountuseridtarget;
        this.status = status;
        this.email = email;
        this.subject = subject;
        this.message = message;
        this.createdate = createdate;
        this.emaillastsentdate = emaillastsentdate;
        this.friendinvitationkey = friendinvitationkey;
    }



    // Property accessors

    public int getFriendinvitationid() {
        return this.friendinvitationid;
    }

    public void setFriendinvitationid(int friendinvitationid) {
        this.friendinvitationid = friendinvitationid;
    }

    public int getAccountuseridsource() {
        return this.accountuseridsource;
    }

    public void setAccountuseridsource(int accountuseridsource) {
        this.accountuseridsource = accountuseridsource;
    }

    public int getAccountuseridtarget() {
        return this.accountuseridtarget;
    }

    public void setAccountuseridtarget(int accountuseridtarget) {
        this.accountuseridtarget = accountuseridtarget;
    }

    public int getStatus() {
        return this.status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSubject() {
        return this.subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Date getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    public Date getEmaillastsentdate() {
        return this.emaillastsentdate;
    }

    public void setEmaillastsentdate(Date emaillastsentdate) {
        this.emaillastsentdate = emaillastsentdate;
    }

    public String getFriendinvitationkey() {
        return this.friendinvitationkey;
    }

    public void setFriendinvitationkey(String friendinvitationkey) {
        this.friendinvitationkey = friendinvitationkey;
    }









}
