package reger.dao;

import java.util.Set;
import java.util.HashSet;
// Generated Mar 7, 2006 3:42:39 PM by Hibernate Tools 3.1.0.beta4



/**
 * Groups generated by hbm2java
 */

public class Groups  implements java.io.Serializable {


    // Fields

     private int groupid;
     private String name;
     private String description;
     private int entriesareprivate;
     private boolean membershipismoderated;
     private int plid;
     private int accountuserid;



    // Constructors

    /** default constructor */
    public Groups() {
    }

	/** minimal constructor */
    public Groups(int groupid) {
        this.groupid = groupid;
    }

    /** full constructor */
    public Groups(int groupid, String name, String description, Integer entriesareprivate, boolean membershipismoderated, Integer plid, Integer accountuserid) {
        this.groupid = groupid;
        this.name = name;
        this.description = description;
        this.entriesareprivate = entriesareprivate;
        this.membershipismoderated = membershipismoderated;
        this.plid = plid;
        this.accountuserid = accountuserid;
    }



    // Property accessors

    public int getGroupid() {
        return this.groupid;
    }

    public void setGroupid(int groupid) {
        this.groupid = groupid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getEntriesareprivate() {
        return this.entriesareprivate;
    }

    public void setEntriesareprivate(int entriesareprivate) {
        this.entriesareprivate = entriesareprivate;
    }

    public boolean getMembershipismoderated() {
        return this.membershipismoderated;
    }

    public void setMembershipismoderated(boolean membershipismoderated) {
        this.membershipismoderated = membershipismoderated;
    }

    public int getPlid() {
        return this.plid;
    }

    public void setPlid(int plid) {
        this.plid = plid;
    }

    public int getAccountuserid() {
        return this.accountuserid;
    }

    public void setAccountuserid(int accountuserid) {
        this.accountuserid = accountuserid;
    }









}
