package reger.dao;
// Generated Mar 7, 2006 3:43:15 PM by Hibernate Tools 3.1.0.beta4



/**
 * Help generated by hbm2java
 */

public class Help  implements java.io.Serializable {


    // Fields    

     private int helpid;
     private String helpkey;
     private int helpsection;
     private int eventtypeid;
     private String title;
     private String body;


    // Constructors

    /** default constructor */
    public Help() {
    }

	/** minimal constructor */
    public Help(int helpid) {
        this.helpid = helpid;
    }
    
    /** full constructor */
    public Help(int helpid, String helpkey, Integer helpsection, Integer eventtypeid, String title, String body) {
        this.helpid = helpid;
        this.helpkey = helpkey;
        this.helpsection = helpsection;
        this.eventtypeid = eventtypeid;
        this.title = title;
        this.body = body;
    }
    

   
    // Property accessors

    public int getHelpid() {
        return this.helpid;
    }
    
    public void setHelpid(int helpid) {
        this.helpid = helpid;
    }

    public String getHelpkey() {
        return this.helpkey;
    }
    
    public void setHelpkey(String helpkey) {
        this.helpkey = helpkey;
    }

    public int getHelpsection() {
        return this.helpsection;
    }
    
    public void setHelpsection(int helpsection) {
        this.helpsection = helpsection;
    }

    public int getEventtypeid() {
        return this.eventtypeid;
    }
    
    public void setEventtypeid(int eventtypeid) {
        this.eventtypeid = eventtypeid;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
   








}
