package reger.dao;

import java.util.Set;
import java.util.HashSet;
// Generated Mar 7, 2006 3:42:51 PM by Hibernate Tools 3.1.0.beta4



/**
 * Image generated by hbm2java
 */

public class Image  implements java.io.Serializable {


    // Fields

     private int imageid;
     private int eventid;
     private int accountuserid;
     private String image;
     private String description;
     private int sizeinbytes;
     private int imageorder;
     private String originalfilename;
     private int accountid;
     private String filename;

    //Association
    private Set<Tag> tags = new HashSet<Tag>();
    public Set<Tag> getTags() {
        return tags;
    }
    public void setTags(Set<Tag> tags) {
        this.tags = tags;
    }

    //Association
    private Set<Polarhrm> polarhrms = new HashSet<Polarhrm>();
    public Set<Polarhrm> getPolarhrms() {
        return polarhrms;
    }
    public void setPolarhrms(Set<Polarhrm> polarhrms) {
        this.polarhrms = polarhrms;
    }

    // Constructors

    /** default constructor */
    public Image() {
    }

	/** minimal constructor */
    public Image(int imageid, int eventid, int accountuserid, String image, int sizeinbytes, int accountid) {
        this.imageid = imageid;
        this.eventid = eventid;
        this.accountuserid = accountuserid;
        this.image = image;
        this.sizeinbytes = sizeinbytes;
        this.accountid = accountid;
    }

    /** full constructor */
    public Image(int imageid, int eventid, int accountuserid, String image, String description, int sizeinbytes, Integer imageorder, String originalfilename, int accountid, String filename) {
        this.imageid = imageid;
        this.eventid = eventid;
        this.accountuserid = accountuserid;
        this.image = image;
        this.description = description;
        this.sizeinbytes = sizeinbytes;
        this.imageorder = imageorder;
        this.originalfilename = originalfilename;
        this.accountid = accountid;
        this.filename = filename;
    }



    // Property accessors

    public int getImageid() {
        return this.imageid;
    }

    public void setImageid(int imageid) {
        this.imageid = imageid;
    }

    public int getEventid() {
        return this.eventid;
    }

    public void setEventid(int eventid) {
        this.eventid = eventid;
    }

    public int getAccountuserid() {
        return this.accountuserid;
    }

    public void setAccountuserid(int accountuserid) {
        this.accountuserid = accountuserid;
    }

    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getSizeinbytes() {
        return this.sizeinbytes;
    }

    public void setSizeinbytes(int sizeinbytes) {
        this.sizeinbytes = sizeinbytes;
    }

    public int getImageorder() {
        return this.imageorder;
    }

    public void setImageorder(int imageorder) {
        this.imageorder = imageorder;
    }

    public String getOriginalfilename() {
        return this.originalfilename;
    }

    public void setOriginalfilename(String originalfilename) {
        this.originalfilename = originalfilename;
    }

    public int getAccountid() {
        return this.accountid;
    }

    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }

    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }









}
