package reger.dao;
// Generated Mar 7, 2006 3:43:12 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.Set;
import java.util.HashSet;


/**
 * Linkrot generated by hbm2java
 */

public class Linkrot  implements java.io.Serializable {


    // Fields    

     private int linkrotid;
     private String url;
     private String keywords;
     private Date lastcheckeddate;
     private boolean isbroken;
     private int httpstatuscode;

    //Association
    private Set<Linkrotrecommendation> linkrotrecommendations = new HashSet<Linkrotrecommendation>();
    public Set<Linkrotrecommendation> getLinkrotrecommendations() {
        return linkrotrecommendations;
    }
    public void setLinkrotrecommendations(Set<Linkrotrecommendation> linkrotrecommendations) {
        this.linkrotrecommendations = linkrotrecommendations;
    }

    // Constructors

    /** default constructor */
    public Linkrot() {
    }

    /** minimal constructor */
    public Linkrot(int linkrotid) {
        this.linkrotid = linkrotid;
    }

    /** full constructor */
    public Linkrot(int linkrotid, String url, String keywords, Date lastcheckeddate, boolean isbroken, Integer httpstatuscode) {
        this.linkrotid = linkrotid;
        this.url = url;
        this.keywords = keywords;
        this.lastcheckeddate = lastcheckeddate;
        this.isbroken = isbroken;
        this.httpstatuscode = httpstatuscode;
    }



    // Property accessors

    public int getLinkrotid() {
        return this.linkrotid;
    }

    public void setLinkrotid(int linkrotid) {
        this.linkrotid = linkrotid;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getKeywords() {
        return this.keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    public Date getLastcheckeddate() {
        return this.lastcheckeddate;
    }

    public void setLastcheckeddate(Date lastcheckeddate) {
        this.lastcheckeddate = lastcheckeddate;
    }

    public boolean getIsbroken() {
        return this.isbroken;
    }

    public void setIsbroken(boolean isbroken) {
        this.isbroken = isbroken;
    }

    public int getHttpstatuscode() {
        return this.httpstatuscode;
    }

    public void setHttpstatuscode(int httpstatuscode) {
        this.httpstatuscode = httpstatuscode;
    }









}
