package reger.dao;
// Generated Mar 7, 2006 3:42:55 PM by Hibernate Tools 3.1.0.beta4



/**
 * Linkrotrecommendation generated by hbm2java
 */

public class Linkrotrecommendation  implements java.io.Serializable {


    // Fields    

     private int linkrotrecommendationid;
     private int linkrotid;
     private String url;
     private String source;


    // Constructors

    /** default constructor */
    public Linkrotrecommendation() {
    }

	/** minimal constructor */
    public Linkrotrecommendation(int linkrotrecommendationid) {
        this.linkrotrecommendationid = linkrotrecommendationid;
    }
    
    /** full constructor */
    public Linkrotrecommendation(int linkrotrecommendationid, Integer linkrotid, String url, String source) {
        this.linkrotrecommendationid = linkrotrecommendationid;
        this.linkrotid = linkrotid;
        this.url = url;
        this.source = source;
    }
    

   
    // Property accessors

    public int getLinkrotrecommendationid() {
        return this.linkrotrecommendationid;
    }
    
    public void setLinkrotrecommendationid(int linkrotrecommendationid) {
        this.linkrotrecommendationid = linkrotrecommendationid;
    }

    public int getLinkrotid() {
        return this.linkrotid;
    }
    
    public void setLinkrotid(int linkrotid) {
        this.linkrotid = linkrotid;
    }

    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
   








}
