package reger.dao;
// Generated Mar 7, 2006 3:42:49 PM by Hibernate Tools 3.1.0.beta4



/**
 * Location generated by hbm2java
 */

public class Location  implements java.io.Serializable {


    // Fields    

     private int locationid;
     private String locationname;
     private int accountid;
     private int latdeg;
     private int latmin;
     private int latsec;
     private int latns;
     private int londeg;
     private int lonmin;
     private int lonsec;
     private int lonew;
     private String city;
     private String state;
     private String country;
     private Double latitude;
     private Double longitude;


    // Constructors

    /** default constructor */
    public Location() {
    }

	/** minimal constructor */
    public Location(int locationid, String locationname, int accountid) {
        this.locationid = locationid;
        this.locationname = locationname;
        this.accountid = accountid;
    }
    
    /** full constructor */
    public Location(int locationid, String locationname, int accountid, Integer latdeg, Integer latmin, Integer latsec, Integer latns, Integer londeg, Integer lonmin, Integer lonsec, Integer lonew, String city, String state, String country, Double latitude, Double longitude) {
        this.locationid = locationid;
        this.locationname = locationname;
        this.accountid = accountid;
        this.latdeg = latdeg;
        this.latmin = latmin;
        this.latsec = latsec;
        this.latns = latns;
        this.londeg = londeg;
        this.lonmin = lonmin;
        this.lonsec = lonsec;
        this.lonew = lonew;
        this.city = city;
        this.state = state;
        this.country = country;
        this.latitude = latitude;
        this.longitude = longitude;
    }
    

   
    // Property accessors

    public int getLocationid() {
        return this.locationid;
    }
    
    public void setLocationid(int locationid) {
        this.locationid = locationid;
    }

    public String getLocationname() {
        return this.locationname;
    }
    
    public void setLocationname(String locationname) {
        this.locationname = locationname;
    }

    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }

    public int getLatdeg() {
        return this.latdeg;
    }
    
    public void setLatdeg(int latdeg) {
        this.latdeg = latdeg;
    }

    public int getLatmin() {
        return this.latmin;
    }
    
    public void setLatmin(int latmin) {
        this.latmin = latmin;
    }

    public int getLatsec() {
        return this.latsec;
    }
    
    public void setLatsec(int latsec) {
        this.latsec = latsec;
    }

    public int getLatns() {
        return this.latns;
    }
    
    public void setLatns(int latns) {
        this.latns = latns;
    }

    public int getLondeg() {
        return this.londeg;
    }
    
    public void setLondeg(int londeg) {
        this.londeg = londeg;
    }

    public int getLonmin() {
        return this.lonmin;
    }
    
    public void setLonmin(int lonmin) {
        this.lonmin = lonmin;
    }

    public int getLonsec() {
        return this.lonsec;
    }
    
    public void setLonsec(int lonsec) {
        this.lonsec = lonsec;
    }

    public int getLonew() {
        return this.lonew;
    }
    
    public void setLonew(int lonew) {
        this.lonew = lonew;
    }

    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
   








}
