package reger.dao;
// Generated Mar 7, 2006 3:43:03 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * Loginhistory generated by hbm2java
 */

public class Loginhistory  implements java.io.Serializable {


    // Fields    

     private int loginhistoryid;
     private int accountuserid;
     private Date date;
     private String usertype;
     private String enteredpassword;
     private boolean success;


    // Constructors

    /** default constructor */
    public Loginhistory() {
    }

	/** minimal constructor */
    public Loginhistory(int loginhistoryid, int accountuserid, Date date, String enteredpassword) {
        this.loginhistoryid = loginhistoryid;
        this.accountuserid = accountuserid;
        this.date = date;
        this.enteredpassword = enteredpassword;
    }
    
    /** full constructor */
    public Loginhistory(int loginhistoryid, int accountuserid, Date date, String usertype, String enteredpassword, boolean success) {
        this.loginhistoryid = loginhistoryid;
        this.accountuserid = accountuserid;
        this.date = date;
        this.usertype = usertype;
        this.enteredpassword = enteredpassword;
        this.success = success;
    }
    

   
    // Property accessors

    public int getLoginhistoryid() {
        return this.loginhistoryid;
    }
    
    public void setLoginhistoryid(int loginhistoryid) {
        this.loginhistoryid = loginhistoryid;
    }

    public int getAccountuserid() {
        return this.accountuserid;
    }
    
    public void setAccountuserid(int accountuserid) {
        this.accountuserid = accountuserid;
    }

    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    public String getEnteredpassword() {
        return this.enteredpassword;
    }
    
    public void setEnteredpassword(String enteredpassword) {
        this.enteredpassword = enteredpassword;
    }

    public boolean getSuccess() {
        return this.success;
    }
    
    public void setSuccess(boolean success) {
        this.success = success;
    }
   








}
