package reger.dao;

import java.util.Set;
import java.util.HashSet;
// Generated Mar 7, 2006 3:43:23 PM by Hibernate Tools 3.1.0.beta4



/**
 * Megachart generated by hbm2java
 */

public class Megachart  implements java.io.Serializable {


    // Fields    

     private int megachartid;
     private String chartname;
     private int xeventtypeid;
     private int xlogid;
     private int xmegafieldid;
     private int yaxiswhattodo;
     private int chartsize;
     private int charttype;
     private int daterange;
     private int lastxdays;
     private int lastxweeks;
     private int lastxmonths;
     private int lastxyears;
     private int daterangefromyyyy;
     private int daterangefrommm;
     private int daterangefromdd;
     private int daterangetoyyyy;
     private int daterangetomm;
     private int daterangetodd;
     private int daterangesavedsearchid;
     private int accountid;

    //Association
    private Set<Megachartyaxis> megachartyaxes = new HashSet<Megachartyaxis>();
    public Set<Megachartyaxis> getMegachartyaxes() {
        return megachartyaxes;
    }
    public void setMegachartyaxes(Set<Megachartyaxis> megachartyaxes) {
        this.megachartyaxes = megachartyaxes;
    }

    // Constructors

    /** default constructor */
    public Megachart() {
    }

    
    /** full constructor */
    public Megachart(int megachartid, String chartname, int xeventtypeid, int xlogid, int xmegafieldid, int yaxiswhattodo, int chartsize, int charttype, int daterange, int lastxdays, int lastxweeks, int lastxmonths, int lastxyears, int daterangefromyyyy, int daterangefrommm, int daterangefromdd, int daterangetoyyyy, int daterangetomm, int daterangetodd, int daterangesavedsearchid, int accountid) {
        this.megachartid = megachartid;
        this.chartname = chartname;
        this.xeventtypeid = xeventtypeid;
        this.xlogid = xlogid;
        this.xmegafieldid = xmegafieldid;
        this.yaxiswhattodo = yaxiswhattodo;
        this.chartsize = chartsize;
        this.charttype = charttype;
        this.daterange = daterange;
        this.lastxdays = lastxdays;
        this.lastxweeks = lastxweeks;
        this.lastxmonths = lastxmonths;
        this.lastxyears = lastxyears;
        this.daterangefromyyyy = daterangefromyyyy;
        this.daterangefrommm = daterangefrommm;
        this.daterangefromdd = daterangefromdd;
        this.daterangetoyyyy = daterangetoyyyy;
        this.daterangetomm = daterangetomm;
        this.daterangetodd = daterangetodd;
        this.daterangesavedsearchid = daterangesavedsearchid;
        this.accountid = accountid;
    }
    

   
    // Property accessors

    public int getMegachartid() {
        return this.megachartid;
    }
    
    public void setMegachartid(int megachartid) {
        this.megachartid = megachartid;
    }

    public String getChartname() {
        return this.chartname;
    }
    
    public void setChartname(String chartname) {
        this.chartname = chartname;
    }

    public int getXeventtypeid() {
        return this.xeventtypeid;
    }
    
    public void setXeventtypeid(int xeventtypeid) {
        this.xeventtypeid = xeventtypeid;
    }

    public int getXlogid() {
        return this.xlogid;
    }
    
    public void setXlogid(int xlogid) {
        this.xlogid = xlogid;
    }

    public int getXmegafieldid() {
        return this.xmegafieldid;
    }
    
    public void setXmegafieldid(int xmegafieldid) {
        this.xmegafieldid = xmegafieldid;
    }

    public int getYaxiswhattodo() {
        return this.yaxiswhattodo;
    }
    
    public void setYaxiswhattodo(int yaxiswhattodo) {
        this.yaxiswhattodo = yaxiswhattodo;
    }

    public int getChartsize() {
        return this.chartsize;
    }
    
    public void setChartsize(int chartsize) {
        this.chartsize = chartsize;
    }

    public int getCharttype() {
        return this.charttype;
    }
    
    public void setCharttype(int charttype) {
        this.charttype = charttype;
    }

    public int getDaterange() {
        return this.daterange;
    }
    
    public void setDaterange(int daterange) {
        this.daterange = daterange;
    }

    public int getLastxdays() {
        return this.lastxdays;
    }
    
    public void setLastxdays(int lastxdays) {
        this.lastxdays = lastxdays;
    }

    public int getLastxweeks() {
        return this.lastxweeks;
    }
    
    public void setLastxweeks(int lastxweeks) {
        this.lastxweeks = lastxweeks;
    }

    public int getLastxmonths() {
        return this.lastxmonths;
    }
    
    public void setLastxmonths(int lastxmonths) {
        this.lastxmonths = lastxmonths;
    }

    public int getLastxyears() {
        return this.lastxyears;
    }
    
    public void setLastxyears(int lastxyears) {
        this.lastxyears = lastxyears;
    }

    public int getDaterangefromyyyy() {
        return this.daterangefromyyyy;
    }
    
    public void setDaterangefromyyyy(int daterangefromyyyy) {
        this.daterangefromyyyy = daterangefromyyyy;
    }

    public int getDaterangefrommm() {
        return this.daterangefrommm;
    }
    
    public void setDaterangefrommm(int daterangefrommm) {
        this.daterangefrommm = daterangefrommm;
    }

    public int getDaterangefromdd() {
        return this.daterangefromdd;
    }
    
    public void setDaterangefromdd(int daterangefromdd) {
        this.daterangefromdd = daterangefromdd;
    }

    public int getDaterangetoyyyy() {
        return this.daterangetoyyyy;
    }
    
    public void setDaterangetoyyyy(int daterangetoyyyy) {
        this.daterangetoyyyy = daterangetoyyyy;
    }

    public int getDaterangetomm() {
        return this.daterangetomm;
    }
    
    public void setDaterangetomm(int daterangetomm) {
        this.daterangetomm = daterangetomm;
    }

    public int getDaterangetodd() {
        return this.daterangetodd;
    }
    
    public void setDaterangetodd(int daterangetodd) {
        this.daterangetodd = daterangetodd;
    }

    public int getDaterangesavedsearchid() {
        return this.daterangesavedsearchid;
    }
    
    public void setDaterangesavedsearchid(int daterangesavedsearchid) {
        this.daterangesavedsearchid = daterangesavedsearchid;
    }

    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }
   








}
