package reger.dao;
// Generated Mar 7, 2006 3:42:59 PM by Hibernate Tools 3.1.0.beta4



/**
 * Megaoption generated by hbm2java
 */

public class Megaoption  implements java.io.Serializable {


    // Fields    

     private int megaoptionid;
     private int logid;
     private int megafieldid;
     private String optiontext;
     private String optiontextdisplayoverride;
     private boolean isdefault;
     private boolean isactive;


    // Constructors

    /** default constructor */
    public Megaoption() {
    }

	/** minimal constructor */
    public Megaoption(int megaoptionid, String optiontext) {
        this.megaoptionid = megaoptionid;
        this.optiontext = optiontext;
    }
    
    /** full constructor */
    public Megaoption(int megaoptionid, Integer logid, Integer megafieldid, String optiontext, String optiontextdisplayoverride, boolean isdefault, boolean isactive) {
        this.megaoptionid = megaoptionid;
        this.logid = logid;
        this.megafieldid = megafieldid;
        this.optiontext = optiontext;
        this.optiontextdisplayoverride = optiontextdisplayoverride;
        this.isdefault = isdefault;
        this.isactive = isactive;
    }
    

   
    // Property accessors

    public int getMegaoptionid() {
        return this.megaoptionid;
    }
    
    public void setMegaoptionid(int megaoptionid) {
        this.megaoptionid = megaoptionid;
    }

    public int getLogid() {
        return this.logid;
    }
    
    public void setLogid(int logid) {
        this.logid = logid;
    }

    public int getMegafieldid() {
        return this.megafieldid;
    }
    
    public void setMegafieldid(int megafieldid) {
        this.megafieldid = megafieldid;
    }

    public String getOptiontext() {
        return this.optiontext;
    }
    
    public void setOptiontext(String optiontext) {
        this.optiontext = optiontext;
    }

    public String getOptiontextdisplayoverride() {
        return this.optiontextdisplayoverride;
    }
    
    public void setOptiontextdisplayoverride(String optiontextdisplayoverride) {
        this.optiontextdisplayoverride = optiontextdisplayoverride;
    }

    public boolean getIsdefault() {
        return this.isdefault;
    }
    
    public void setIsdefault(boolean isdefault) {
        this.isdefault = isdefault;
    }

    public boolean getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(boolean isactive) {
        this.isactive = isactive;
    }
   








}
