package reger.dao;
// Generated Mar 7, 2006 3:43:07 PM by Hibernate Tools 3.1.0.beta4



/**
 * Megafieldparam generated by hbm2java
 */

public class Megafieldparam  implements java.io.Serializable {


    // Fields    

     private int megafieldparamid;
     private String oneworddatabasekey;
     private int megafieldid;
     private String value;


    // Constructors

    /** default constructor */
    public Megafieldparam() {
    }

    
    /** full constructor */
    public Megafieldparam(int megafieldparamid, String oneworddatabasekey, int megafieldid, String value) {
        this.megafieldparamid = megafieldparamid;
        this.oneworddatabasekey = oneworddatabasekey;
        this.megafieldid = megafieldid;
        this.value = value;
    }
    

   
    // Property accessors

    public int getMegafieldparamid() {
        return this.megafieldparamid;
    }
    
    public void setMegafieldparamid(int megafieldparamid) {
        this.megafieldparamid = megafieldparamid;
    }

    public String getOneworddatabasekey() {
        return this.oneworddatabasekey;
    }
    
    public void setOneworddatabasekey(String oneworddatabasekey) {
        this.oneworddatabasekey = oneworddatabasekey;
    }

    public int getMegafieldid() {
        return this.megafieldid;
    }
    
    public void setMegafieldid(int megafieldid) {
        this.megafieldid = megafieldid;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
   








}
