package reger.dao;

import java.util.Set;
import java.util.HashSet;
// Generated Mar 7, 2006 3:42:47 PM by Hibernate Tools 3.1.0.beta4



/**
 * Megafield generated by hbm2java
 */

public class Megafield  implements java.io.Serializable {


    // Fields    

     private int megafieldid;
     private int fieldtype;
     private int eventtypeid;
     private String fieldname;
     private String fielddescription;
     private int megadatatypeid;
     private boolean isrequired;
     private int logid;


    //Association
    private Set<Megafieldparam> megafieldparams = new HashSet<Megafieldparam>();
    public Set<Megafieldparam> getMegafieldparams() {
        return megafieldparams;
    }
    public void setMegafieldparams(Set<Megafieldparam> megafieldparams) {
        this.megafieldparams = megafieldparams;
    }

    // Constructors

    /** default constructor */
    public Megafield() {
    }

	/** minimal constructor */
    public Megafield(int megafieldid, int logid) {
        this.megafieldid = megafieldid;
        this.logid = logid;
    }
    
    /** full constructor */
    public Megafield(int megafieldid, Integer fieldtype, Integer eventtypeid, String fieldname, String fielddescription, Integer megadatatypeid, boolean isrequired, int logid) {
        this.megafieldid = megafieldid;
        this.fieldtype = fieldtype;
        this.eventtypeid = eventtypeid;
        this.fieldname = fieldname;
        this.fielddescription = fielddescription;
        this.megadatatypeid = megadatatypeid;
        this.isrequired = isrequired;
        this.logid = logid;
    }
    

   
    // Property accessors

    public int getMegafieldid() {
        return this.megafieldid;
    }
    
    public void setMegafieldid(int megafieldid) {
        this.megafieldid = megafieldid;
    }

    public int getFieldtype() {
        return this.fieldtype;
    }
    
    public void setFieldtype(int fieldtype) {
        this.fieldtype = fieldtype;
    }

    public int getEventtypeid() {
        return this.eventtypeid;
    }
    
    public void setEventtypeid(int eventtypeid) {
        this.eventtypeid = eventtypeid;
    }

    public String getFieldname() {
        return this.fieldname;
    }
    
    public void setFieldname(String fieldname) {
        this.fieldname = fieldname;
    }

    public String getFielddescription() {
        return this.fielddescription;
    }
    
    public void setFielddescription(String fielddescription) {
        this.fielddescription = fielddescription;
    }

    public int getMegadatatypeid() {
        return this.megadatatypeid;
    }
    
    public void setMegadatatypeid(int megadatatypeid) {
        this.megadatatypeid = megadatatypeid;
    }

    public boolean getIsrequired() {
        return this.isrequired;
    }
    
    public void setIsrequired(boolean isrequired) {
        this.isrequired = isrequired;
    }

    public int getLogid() {
        return this.logid;
    }
    
    public void setLogid(int logid) {
        this.logid = logid;
    }
   








}
