package reger.dao;

import java.util.Set;
import java.util.HashSet;
// Generated Mar 7, 2006 3:42:41 PM by Hibernate Tools 3.1.0.beta4



/**
 * Megalog generated by hbm2java
 */

public class Megalog  implements java.io.Serializable {


    // Fields    

     private int logid;
     private int accountid;
     private int eventtypeid;
     private String name;
     private int logaccess;
     private String password;
     private String message;
     private boolean showonhomepage;
     private int maintemplateid;
     private int entlisttemplateid;
     private int nestednavparenttype;
     private int nestednavparentid;
     private int nestednavorder;
     private String fieldorder;
     private String hiddenfields;
     private String customdomain1;
     private String customdomain2;
     private String customdomain3;



    //Association
    private Set<Megadefault> megadefaults = new HashSet<Megadefault>();
    public Set<Megadefault> getMegadefaults() {
        return megadefaults;
    }
    public void setMegadefaults(Set<Megadefault> megadefaults) {
        this.megadefaults = megadefaults;
    }

    //Association
    private Set<Megaoption> megaoptions = new HashSet<Megaoption>();
    public Set<Megaoption> getMegaoptions() {
        return megaoptions;
    }
    public void setMegaoptions(Set<Megaoption> megaoptions) {
        this.megaoptions = megaoptions;
    }


    // Constructors

    /** default constructor */
    public Megalog() {
    }

	/** minimal constructor */
    public Megalog(int logid, int maintemplateid, int entlisttemplateid, int nestednavparenttype, int nestednavparentid, int nestednavorder) {
        this.logid = logid;
        this.maintemplateid = maintemplateid;
        this.entlisttemplateid = entlisttemplateid;
        this.nestednavparenttype = nestednavparenttype;
        this.nestednavparentid = nestednavparentid;
        this.nestednavorder = nestednavorder;
    }
    


   
    // Property accessors

    public int getLogid() {
        return this.logid;
    }
    
    public void setLogid(int logid) {
        this.logid = logid;
    }

    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }

    public int getEventtypeid() {
        return this.eventtypeid;
    }
    
    public void setEventtypeid(int eventtypeid) {
        this.eventtypeid = eventtypeid;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public int getLogaccess() {
        return this.logaccess;
    }
    
    public void setLogaccess(int logaccess) {
        this.logaccess = logaccess;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    public boolean getShowonhomepage() {
        return this.showonhomepage;
    }
    
    public void setShowonhomepage(boolean showonhomepage) {
        this.showonhomepage = showonhomepage;
    }

    public int getMaintemplateid() {
        return this.maintemplateid;
    }
    
    public void setMaintemplateid(int maintemplateid) {
        this.maintemplateid = maintemplateid;
    }

    public int getEntlisttemplateid() {
        return this.entlisttemplateid;
    }
    
    public void setEntlisttemplateid(int entlisttemplateid) {
        this.entlisttemplateid = entlisttemplateid;
    }

    public int getNestednavparenttype() {
        return this.nestednavparenttype;
    }
    
    public void setNestednavparenttype(int nestednavparenttype) {
        this.nestednavparenttype = nestednavparenttype;
    }

    public int getNestednavparentid() {
        return this.nestednavparentid;
    }
    
    public void setNestednavparentid(int nestednavparentid) {
        this.nestednavparentid = nestednavparentid;
    }

    public int getNestednavorder() {
        return this.nestednavorder;
    }
    
    public void setNestednavorder(int nestednavorder) {
        this.nestednavorder = nestednavorder;
    }

    public String getFieldorder() {
        return this.fieldorder;
    }
    
    public void setFieldorder(String fieldorder) {
        this.fieldorder = fieldorder;
    }

    public String getHiddenfields() {
        return this.hiddenfields;
    }
    
    public void setHiddenfields(String hiddenfields) {
        this.hiddenfields = hiddenfields;
    }


    public String getCustomdomain1() {
        return customdomain1;
    }

    public void setCustomdomain1(String customdomain1) {
        this.customdomain1 = customdomain1;
    }

    public String getCustomdomain2() {
        return customdomain2;
    }

    public void setCustomdomain2(String customdomain2) {
        this.customdomain2 = customdomain2;
    }

    public String getCustomdomain3() {
        return customdomain3;
    }

    public void setCustomdomain3(String customdomain3) {
        this.customdomain3 = customdomain3;
    }
}
