package reger.dao;
// Generated Mar 7, 2006 3:42:47 PM by Hibernate Tools 3.1.0.beta4



/**
 * Pagenotfound generated by hbm2java
 */

public class Pagenotfound  implements java.io.Serializable {


    // Fields    

     private int pagenotfoundid;
     private String pagename;
     private int count;
     private String mostrecentreferer;


    // Constructors

    /** default constructor */
    public Pagenotfound() {
    }

	/** minimal constructor */
    public Pagenotfound(int pagenotfoundid) {
        this.pagenotfoundid = pagenotfoundid;
    }
    
    /** full constructor */
    public Pagenotfound(int pagenotfoundid, String pagename, Integer count, String mostrecentreferer) {
        this.pagenotfoundid = pagenotfoundid;
        this.pagename = pagename;
        this.count = count;
        this.mostrecentreferer = mostrecentreferer;
    }
    

   
    // Property accessors

    public int getPagenotfoundid() {
        return this.pagenotfoundid;
    }
    
    public void setPagenotfoundid(int pagenotfoundid) {
        this.pagenotfoundid = pagenotfoundid;
    }

    public String getPagename() {
        return this.pagename;
    }
    
    public void setPagename(String pagename) {
        this.pagename = pagename;
    }

    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }

    public String getMostrecentreferer() {
        return this.mostrecentreferer;
    }
    
    public void setMostrecentreferer(String mostrecentreferer) {
        this.mostrecentreferer = mostrecentreferer;
    }
   








}
