package reger.dao;

import java.util.Set;
import java.util.HashSet;
// Generated Mar 7, 2006 3:42:42 PM by Hibernate Tools 3.1.0.beta4



/**
 * Pl generated by hbm2java
 */

public class Pl  implements java.io.Serializable {


    // Fields    

     private int plid;
     private String plname;
     private String plbasedomain;
     private String titlebar;
     private String comments;
     private boolean islive;
     private boolean issignupenabled;
     private boolean iscontentflaggingon;
     private boolean doesflaggedcontentneedtobeapproved;
     private boolean doallpostsneedtobeapproved;
     private boolean usedynamicdns;
     private int defaultaccounttypeidatsignup;
     private Long defaultmaxspaceinbytes;
     private String termsofservice;
     private boolean newaccountsrequireadminapproval;
     private boolean forcelogintoviewsites;
     private boolean isweblogscompingon;
     private String emailtonotifyofnewaccounts;
     private String emailapiuniqueidentifier;
     private long defaultmaxbandwidth;
     private int minpasswordchars;
     private int minpassworduppercasechars;
     private int minpasswordlowercasechars;
     private int minpasswordspecialchars;
     private int minpasswordnumericchars;
     private boolean ispasswordsentviaemail;
     private String termsofuselinktext;
     private String feedbacklinktext;
     private boolean doapplyplusertemplatetopro;
     private int publicsitetemplateid;
     private int entlisttemplateid;
     private int hptemplateid;
     private int marketingsitetemplateid;
     private int marketingsitehptemplateid;
     private int defaulteventtypeid;
     private String encryptedlicense;
     private Double baseaccountprice;
     private Double priceper100mbstorage;
     private Double pricepergbbandwidth;
     private boolean istrackbackenabled;
     private int plusertemplateid;
     private String bannerone;
     private String bannertwo;
     private String bannerthree;
     private boolean showbannertagsonpro;
     private boolean isemailactivationofaccountsrequired;
     private String emailtextactivationmessage;
     private String emailsubjectactivationmessage;
     private String emailtextwelcomemessage;
     private String emailsubjectwelcomemessage;
     private String accountupgradeurl;


    //Association
    private Set<Offensivecontentpl> offensivecontentpls = new HashSet<Offensivecontentpl>();
    public Set<Offensivecontentpl> getOffensivecontentpls() {
        return offensivecontentpls;
    }
    public void setOffensivecontentpls(Set<Offensivecontentpl> offensivecontentpls) {
        this.offensivecontentpls = offensivecontentpls;
    }

    //Association
    private Set<Plcontentoverride> plcontentoverrides = new HashSet<Plcontentoverride>();
    public Set<Plcontentoverride> getPlcontentoverrides() {
        return plcontentoverrides;
    }
    public void setPlcontentoverrides(Set<Plcontentoverride> plcontentoverrides) {
        this.plcontentoverrides = plcontentoverrides;
    }

    //Association
    private Set<Plcontentpage> plcontentpages = new HashSet<Plcontentpage>();
    public Set<Plcontentpage> getPlcontentpages() {
        return plcontentpages;
    }
    public void setPlcontentpages(Set<Plcontentpage> plcontentpages) {
        this.plcontentpages = plcontentpages;
    }

    //Association
    private Set<Pldeletearchive> pldeletearchives = new HashSet<Pldeletearchive>();
    public Set<Pldeletearchive> getPldeletearchives() {
        return pldeletearchives;
    }
    public void setPldeletearchives(Set<Pldeletearchive> pldeletearchives) {
        this.pldeletearchives = pldeletearchives;
    }

    //Association
    private Set<Pleventtypeid> pleventtypeids = new HashSet<Pleventtypeid>();
    public Set<Pleventtypeid> getPleventtypeids() {
        return pleventtypeids;
    }
    public void setPleventtypeids(Set<Pleventtypeid> pleventtypeids) {
        this.pleventtypeids = pleventtypeids;
    }

    //Association
    private Set<Plnavhide> plnavhides = new HashSet<Plnavhide>();
    public Set<Plnavhide> getPlnavhides() {
        return plnavhides;
    }
    public void setPlnavhides(Set<Plnavhide> plnavhides) {
        this.plnavhides = plnavhides;
    }

    //Association
    private Set<Plpeer> plpeers = new HashSet<Plpeer>();
    public Set<Plpeer> getPlpeers() {
        return plpeers;
    }
    public void setPlpeers(Set<Plpeer> plpeers) {
        this.plpeers = plpeers;
    }

    // Constructors

    /** default constructor */
    public Pl() {
    }

	/** minimal constructor */
    public Pl(int plid, int defaultaccounttypeidatsignup, long defaultmaxbandwidth, int minpasswordchars, int minpassworduppercasechars, int minpasswordlowercasechars, int minpasswordspecialchars, int minpasswordnumericchars, int publicsitetemplateid, int entlisttemplateid, int hptemplateid, int marketingsitetemplateid, int marketingsitehptemplateid, int defaulteventtypeid, int plusertemplateid) {
        this.plid = plid;
        this.defaultaccounttypeidatsignup = defaultaccounttypeidatsignup;
        this.defaultmaxbandwidth = defaultmaxbandwidth;
        this.minpasswordchars = minpasswordchars;
        this.minpassworduppercasechars = minpassworduppercasechars;
        this.minpasswordlowercasechars = minpasswordlowercasechars;
        this.minpasswordspecialchars = minpasswordspecialchars;
        this.minpasswordnumericchars = minpasswordnumericchars;
        this.publicsitetemplateid = publicsitetemplateid;
        this.entlisttemplateid = entlisttemplateid;
        this.hptemplateid = hptemplateid;
        this.marketingsitetemplateid = marketingsitetemplateid;
        this.marketingsitehptemplateid = marketingsitehptemplateid;
        this.defaulteventtypeid = defaulteventtypeid;
        this.plusertemplateid = plusertemplateid;
    }
    
    /** full constructor */
    public Pl(int plid, String plname, String plbasedomain, String titlebar, String comments, boolean islive, boolean issignupenabled, boolean iscontentflaggingon, boolean doesflaggedcontentneedtobeapproved, boolean doallpostsneedtobeapproved, boolean usedynamicdns, int defaultaccounttypeidatsignup, Long defaultmaxspaceinbytes, String termsofservice, boolean newaccountsrequireadminapproval, boolean forcelogintoviewsites, boolean isweblogscompingon, String emailtonotifyofnewaccounts, String emailapiuniqueidentifier, long defaultmaxbandwidth, int minpasswordchars, int minpassworduppercasechars, int minpasswordlowercasechars, int minpasswordspecialchars, int minpasswordnumericchars, boolean ispasswordsentviaemail, String termsofuselinktext, String feedbacklinktext, boolean doapplyplusertemplatetopro, int publicsitetemplateid, int entlisttemplateid, int hptemplateid, int marketingsitetemplateid, int marketingsitehptemplateid, int defaulteventtypeid, String encryptedlicense, Double baseaccountprice, Double priceper100mbstorage, Double pricepergbbandwidth, boolean istrackbackenabled, int plusertemplateid, String bannerone, String bannertwo, String bannerthree, boolean showbannertagsonpro, boolean isemailactivationofaccountsrequired, String emailtextactivationmessage, String emailsubjectactivationmessage, String emailtextwelcomemessage, String emailsubjectwelcomemessage, String accountupgradeurl) {
        this.plid = plid;
        this.plname = plname;
        this.plbasedomain = plbasedomain;
        this.titlebar = titlebar;
        this.comments = comments;
        this.islive = islive;
        this.issignupenabled = issignupenabled;
        this.iscontentflaggingon = iscontentflaggingon;
        this.doesflaggedcontentneedtobeapproved = doesflaggedcontentneedtobeapproved;
        this.doallpostsneedtobeapproved = doallpostsneedtobeapproved;
        this.usedynamicdns = usedynamicdns;
        this.defaultaccounttypeidatsignup = defaultaccounttypeidatsignup;
        this.defaultmaxspaceinbytes = defaultmaxspaceinbytes;
        this.termsofservice = termsofservice;
        this.newaccountsrequireadminapproval = newaccountsrequireadminapproval;
        this.forcelogintoviewsites = forcelogintoviewsites;
        this.isweblogscompingon = isweblogscompingon;
        this.emailtonotifyofnewaccounts = emailtonotifyofnewaccounts;
        this.emailapiuniqueidentifier = emailapiuniqueidentifier;
        this.defaultmaxbandwidth = defaultmaxbandwidth;
        this.minpasswordchars = minpasswordchars;
        this.minpassworduppercasechars = minpassworduppercasechars;
        this.minpasswordlowercasechars = minpasswordlowercasechars;
        this.minpasswordspecialchars = minpasswordspecialchars;
        this.minpasswordnumericchars = minpasswordnumericchars;
        this.ispasswordsentviaemail = ispasswordsentviaemail;
        this.termsofuselinktext = termsofuselinktext;
        this.feedbacklinktext = feedbacklinktext;
        this.doapplyplusertemplatetopro = doapplyplusertemplatetopro;
        this.publicsitetemplateid = publicsitetemplateid;
        this.entlisttemplateid = entlisttemplateid;
        this.hptemplateid = hptemplateid;
        this.marketingsitetemplateid = marketingsitetemplateid;
        this.marketingsitehptemplateid = marketingsitehptemplateid;
        this.defaulteventtypeid = defaulteventtypeid;
        this.encryptedlicense = encryptedlicense;
        this.baseaccountprice = baseaccountprice;
        this.priceper100mbstorage = priceper100mbstorage;
        this.pricepergbbandwidth = pricepergbbandwidth;
        this.istrackbackenabled = istrackbackenabled;
        this.plusertemplateid = plusertemplateid;
        this.bannerone = bannerone;
        this.bannertwo = bannertwo;
        this.bannerthree = bannerthree;
        this.showbannertagsonpro = showbannertagsonpro;
        this.isemailactivationofaccountsrequired = isemailactivationofaccountsrequired;
        this.emailtextactivationmessage = emailtextactivationmessage;
        this.emailsubjectactivationmessage = emailsubjectactivationmessage;
        this.emailtextwelcomemessage = emailtextwelcomemessage;
        this.emailsubjectwelcomemessage = emailsubjectwelcomemessage;
        this.accountupgradeurl = accountupgradeurl;
    }
    

   
    // Property accessors

    public int getPlid() {
        return this.plid;
    }
    
    public void setPlid(int plid) {
        this.plid = plid;
    }

    public String getPlname() {
        return this.plname;
    }
    
    public void setPlname(String plname) {
        this.plname = plname;
    }

    public String getPlbasedomain() {
        return this.plbasedomain;
    }
    
    public void setPlbasedomain(String plbasedomain) {
        this.plbasedomain = plbasedomain;
    }

    public String getTitlebar() {
        return this.titlebar;
    }
    
    public void setTitlebar(String titlebar) {
        this.titlebar = titlebar;
    }

    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    public boolean getIslive() {
        return this.islive;
    }
    
    public void setIslive(boolean islive) {
        this.islive = islive;
    }

    public boolean getIssignupenabled() {
        return this.issignupenabled;
    }
    
    public void setIssignupenabled(boolean issignupenabled) {
        this.issignupenabled = issignupenabled;
    }

    public boolean getIscontentflaggingon() {
        return this.iscontentflaggingon;
    }
    
    public void setIscontentflaggingon(boolean iscontentflaggingon) {
        this.iscontentflaggingon = iscontentflaggingon;
    }

    public boolean getDoesflaggedcontentneedtobeapproved() {
        return this.doesflaggedcontentneedtobeapproved;
    }
    
    public void setDoesflaggedcontentneedtobeapproved(boolean doesflaggedcontentneedtobeapproved) {
        this.doesflaggedcontentneedtobeapproved = doesflaggedcontentneedtobeapproved;
    }

    public boolean getDoallpostsneedtobeapproved() {
        return this.doallpostsneedtobeapproved;
    }
    
    public void setDoallpostsneedtobeapproved(boolean doallpostsneedtobeapproved) {
        this.doallpostsneedtobeapproved = doallpostsneedtobeapproved;
    }

    public boolean getUsedynamicdns() {
        return this.usedynamicdns;
    }
    
    public void setUsedynamicdns(boolean usedynamicdns) {
        this.usedynamicdns = usedynamicdns;
    }

    public int getDefaultaccounttypeidatsignup() {
        return this.defaultaccounttypeidatsignup;
    }
    
    public void setDefaultaccounttypeidatsignup(int defaultaccounttypeidatsignup) {
        this.defaultaccounttypeidatsignup = defaultaccounttypeidatsignup;
    }

    public Long getDefaultmaxspaceinbytes() {
        return this.defaultmaxspaceinbytes;
    }
    
    public void setDefaultmaxspaceinbytes(Long defaultmaxspaceinbytes) {
        this.defaultmaxspaceinbytes = defaultmaxspaceinbytes;
    }

    public String getTermsofservice() {
        return this.termsofservice;
    }
    
    public void setTermsofservice(String termsofservice) {
        this.termsofservice = termsofservice;
    }

    public boolean getNewaccountsrequireadminapproval() {
        return this.newaccountsrequireadminapproval;
    }
    
    public void setNewaccountsrequireadminapproval(boolean newaccountsrequireadminapproval) {
        this.newaccountsrequireadminapproval = newaccountsrequireadminapproval;
    }

    public boolean getForcelogintoviewsites() {
        return this.forcelogintoviewsites;
    }
    
    public void setForcelogintoviewsites(boolean forcelogintoviewsites) {
        this.forcelogintoviewsites = forcelogintoviewsites;
    }

    public boolean getIsweblogscompingon() {
        return this.isweblogscompingon;
    }
    
    public void setIsweblogscompingon(boolean isweblogscompingon) {
        this.isweblogscompingon = isweblogscompingon;
    }

    public String getEmailtonotifyofnewaccounts() {
        return this.emailtonotifyofnewaccounts;
    }
    
    public void setEmailtonotifyofnewaccounts(String emailtonotifyofnewaccounts) {
        this.emailtonotifyofnewaccounts = emailtonotifyofnewaccounts;
    }

    public String getEmailapiuniqueidentifier() {
        return this.emailapiuniqueidentifier;
    }
    
    public void setEmailapiuniqueidentifier(String emailapiuniqueidentifier) {
        this.emailapiuniqueidentifier = emailapiuniqueidentifier;
    }

    public long getDefaultmaxbandwidth() {
        return this.defaultmaxbandwidth;
    }
    
    public void setDefaultmaxbandwidth(long defaultmaxbandwidth) {
        this.defaultmaxbandwidth = defaultmaxbandwidth;
    }

    public int getMinpasswordchars() {
        return this.minpasswordchars;
    }
    
    public void setMinpasswordchars(int minpasswordchars) {
        this.minpasswordchars = minpasswordchars;
    }

    public int getMinpassworduppercasechars() {
        return this.minpassworduppercasechars;
    }
    
    public void setMinpassworduppercasechars(int minpassworduppercasechars) {
        this.minpassworduppercasechars = minpassworduppercasechars;
    }

    public int getMinpasswordlowercasechars() {
        return this.minpasswordlowercasechars;
    }
    
    public void setMinpasswordlowercasechars(int minpasswordlowercasechars) {
        this.minpasswordlowercasechars = minpasswordlowercasechars;
    }

    public int getMinpasswordspecialchars() {
        return this.minpasswordspecialchars;
    }
    
    public void setMinpasswordspecialchars(int minpasswordspecialchars) {
        this.minpasswordspecialchars = minpasswordspecialchars;
    }

    public int getMinpasswordnumericchars() {
        return this.minpasswordnumericchars;
    }
    
    public void setMinpasswordnumericchars(int minpasswordnumericchars) {
        this.minpasswordnumericchars = minpasswordnumericchars;
    }

    public boolean getIspasswordsentviaemail() {
        return this.ispasswordsentviaemail;
    }
    
    public void setIspasswordsentviaemail(boolean ispasswordsentviaemail) {
        this.ispasswordsentviaemail = ispasswordsentviaemail;
    }

    public String getTermsofuselinktext() {
        return this.termsofuselinktext;
    }
    
    public void setTermsofuselinktext(String termsofuselinktext) {
        this.termsofuselinktext = termsofuselinktext;
    }

    public String getFeedbacklinktext() {
        return this.feedbacklinktext;
    }
    
    public void setFeedbacklinktext(String feedbacklinktext) {
        this.feedbacklinktext = feedbacklinktext;
    }

    public boolean getDoapplyplusertemplatetopro() {
        return this.doapplyplusertemplatetopro;
    }
    
    public void setDoapplyplusertemplatetopro(boolean doapplyplusertemplatetopro) {
        this.doapplyplusertemplatetopro = doapplyplusertemplatetopro;
    }

    public int getPublicsitetemplateid() {
        return this.publicsitetemplateid;
    }
    
    public void setPublicsitetemplateid(int publicsitetemplateid) {
        this.publicsitetemplateid = publicsitetemplateid;
    }

    public int getEntlisttemplateid() {
        return this.entlisttemplateid;
    }
    
    public void setEntlisttemplateid(int entlisttemplateid) {
        this.entlisttemplateid = entlisttemplateid;
    }

    public int getHptemplateid() {
        return this.hptemplateid;
    }
    
    public void setHptemplateid(int hptemplateid) {
        this.hptemplateid = hptemplateid;
    }

    public int getMarketingsitetemplateid() {
        return this.marketingsitetemplateid;
    }
    
    public void setMarketingsitetemplateid(int marketingsitetemplateid) {
        this.marketingsitetemplateid = marketingsitetemplateid;
    }

    public int getMarketingsitehptemplateid() {
        return this.marketingsitehptemplateid;
    }
    
    public void setMarketingsitehptemplateid(int marketingsitehptemplateid) {
        this.marketingsitehptemplateid = marketingsitehptemplateid;
    }

    public int getDefaulteventtypeid() {
        return this.defaulteventtypeid;
    }
    
    public void setDefaulteventtypeid(int defaulteventtypeid) {
        this.defaulteventtypeid = defaulteventtypeid;
    }

    public String getEncryptedlicense() {
        return this.encryptedlicense;
    }
    
    public void setEncryptedlicense(String encryptedlicense) {
        this.encryptedlicense = encryptedlicense;
    }

    public Double getBaseaccountprice() {
        return this.baseaccountprice;
    }
    
    public void setBaseaccountprice(Double baseaccountprice) {
        this.baseaccountprice = baseaccountprice;
    }

    public Double getPriceper100mbstorage() {
        return this.priceper100mbstorage;
    }
    
    public void setPriceper100mbstorage(Double priceper100mbstorage) {
        this.priceper100mbstorage = priceper100mbstorage;
    }

    public Double getPricepergbbandwidth() {
        return this.pricepergbbandwidth;
    }
    
    public void setPricepergbbandwidth(Double pricepergbbandwidth) {
        this.pricepergbbandwidth = pricepergbbandwidth;
    }

    public boolean getIstrackbackenabled() {
        return this.istrackbackenabled;
    }
    
    public void setIstrackbackenabled(boolean istrackbackenabled) {
        this.istrackbackenabled = istrackbackenabled;
    }

    public int getPlusertemplateid() {
        return this.plusertemplateid;
    }
    
    public void setPlusertemplateid(int plusertemplateid) {
        this.plusertemplateid = plusertemplateid;
    }

    public String getBannerone() {
        return this.bannerone;
    }
    
    public void setBannerone(String bannerone) {
        this.bannerone = bannerone;
    }

    public String getBannertwo() {
        return this.bannertwo;
    }
    
    public void setBannertwo(String bannertwo) {
        this.bannertwo = bannertwo;
    }

    public String getBannerthree() {
        return this.bannerthree;
    }
    
    public void setBannerthree(String bannerthree) {
        this.bannerthree = bannerthree;
    }

    public boolean getShowbannertagsonpro() {
        return this.showbannertagsonpro;
    }
    
    public void setShowbannertagsonpro(boolean showbannertagsonpro) {
        this.showbannertagsonpro = showbannertagsonpro;
    }

    public boolean getIsemailactivationofaccountsrequired() {
        return this.isemailactivationofaccountsrequired;
    }
    
    public void setIsemailactivationofaccountsrequired(boolean isemailactivationofaccountsrequired) {
        this.isemailactivationofaccountsrequired = isemailactivationofaccountsrequired;
    }

    public String getEmailtextactivationmessage() {
        return this.emailtextactivationmessage;
    }
    
    public void setEmailtextactivationmessage(String emailtextactivationmessage) {
        this.emailtextactivationmessage = emailtextactivationmessage;
    }

    public String getEmailsubjectactivationmessage() {
        return this.emailsubjectactivationmessage;
    }
    
    public void setEmailsubjectactivationmessage(String emailsubjectactivationmessage) {
        this.emailsubjectactivationmessage = emailsubjectactivationmessage;
    }

    public String getEmailtextwelcomemessage() {
        return this.emailtextwelcomemessage;
    }
    
    public void setEmailtextwelcomemessage(String emailtextwelcomemessage) {
        this.emailtextwelcomemessage = emailtextwelcomemessage;
    }

    public String getEmailsubjectwelcomemessage() {
        return this.emailsubjectwelcomemessage;
    }
    
    public void setEmailsubjectwelcomemessage(String emailsubjectwelcomemessage) {
        this.emailsubjectwelcomemessage = emailsubjectwelcomemessage;
    }

    public String getAccountupgradeurl() {
        return this.accountupgradeurl;
    }
    
    public void setAccountupgradeurl(String accountupgradeurl) {
        this.accountupgradeurl = accountupgradeurl;
    }
   








}
