package reger.dao;
// Generated Mar 7, 2006 3:43:04 PM by Hibernate Tools 3.1.0.beta4



/**
 * Plcontentoverride generated by hbm2java
 */

public class Plcontentoverride  implements java.io.Serializable {


    // Fields    

     private int plcontentoverrideid;
     private int plid;
     private int pljspidtooverride;
     private String content;


    // Constructors

    /** default constructor */
    public Plcontentoverride() {
    }

	/** minimal constructor */
    public Plcontentoverride(int plcontentoverrideid, int plid) {
        this.plcontentoverrideid = plcontentoverrideid;
        this.plid = plid;
    }
    
    /** full constructor */
    public Plcontentoverride(int plcontentoverrideid, int plid, Integer pljspidtooverride, String content) {
        this.plcontentoverrideid = plcontentoverrideid;
        this.plid = plid;
        this.pljspidtooverride = pljspidtooverride;
        this.content = content;
    }
    

   
    // Property accessors

    public int getPlcontentoverrideid() {
        return this.plcontentoverrideid;
    }
    
    public void setPlcontentoverrideid(int plcontentoverrideid) {
        this.plcontentoverrideid = plcontentoverrideid;
    }

    public int getPlid() {
        return this.plid;
    }
    
    public void setPlid(int plid) {
        this.plid = plid;
    }

    public int getPljspidtooverride() {
        return this.pljspidtooverride;
    }
    
    public void setPljspidtooverride(int pljspidtooverride) {
        this.pljspidtooverride = pljspidtooverride;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
   








}
