package reger.dao;
// Generated Mar 7, 2006 3:43:14 PM by Hibernate Tools 3.1.0.beta4



/**
 * Polarhrmdata generated by hbm2java
 */

public class Polarhrmdata  implements java.io.Serializable {


    // Fields    

     private int polarhrmdataid;
     private int polarhrmid;
     private int timeinseconds;
     private int heartrate;
     private Double speed;
     private Double cadence;
     private Double altitude;
     private Double power;
     private Double leftpowerbalance;
     private Double pedalingindex;


    // Constructors

    /** default constructor */
    public Polarhrmdata() {
    }

	/** minimal constructor */
    public Polarhrmdata(int polarhrmdataid, int polarhrmid) {
        this.polarhrmdataid = polarhrmdataid;
        this.polarhrmid = polarhrmid;
    }
    
    /** full constructor */
    public Polarhrmdata(int polarhrmdataid, int polarhrmid, Integer timeinseconds, Integer heartrate, Double speed, Double cadence, Double altitude, Double power, Double leftpowerbalance, Double pedalingindex) {
        this.polarhrmdataid = polarhrmdataid;
        this.polarhrmid = polarhrmid;
        this.timeinseconds = timeinseconds;
        this.heartrate = heartrate;
        this.speed = speed;
        this.cadence = cadence;
        this.altitude = altitude;
        this.power = power;
        this.leftpowerbalance = leftpowerbalance;
        this.pedalingindex = pedalingindex;
    }
    

   
    // Property accessors

    public int getPolarhrmdataid() {
        return this.polarhrmdataid;
    }
    
    public void setPolarhrmdataid(int polarhrmdataid) {
        this.polarhrmdataid = polarhrmdataid;
    }

    public int getPolarhrmid() {
        return this.polarhrmid;
    }
    
    public void setPolarhrmid(int polarhrmid) {
        this.polarhrmid = polarhrmid;
    }

    public int getTimeinseconds() {
        return this.timeinseconds;
    }
    
    public void setTimeinseconds(int timeinseconds) {
        this.timeinseconds = timeinseconds;
    }

    public int getHeartrate() {
        return this.heartrate;
    }
    
    public void setHeartrate(int heartrate) {
        this.heartrate = heartrate;
    }

    public Double getSpeed() {
        return this.speed;
    }
    
    public void setSpeed(Double speed) {
        this.speed = speed;
    }

    public Double getCadence() {
        return this.cadence;
    }
    
    public void setCadence(Double cadence) {
        this.cadence = cadence;
    }

    public Double getAltitude() {
        return this.altitude;
    }
    
    public void setAltitude(Double altitude) {
        this.altitude = altitude;
    }

    public Double getPower() {
        return this.power;
    }
    
    public void setPower(Double power) {
        this.power = power;
    }

    public Double getLeftpowerbalance() {
        return this.leftpowerbalance;
    }
    
    public void setLeftpowerbalance(Double leftpowerbalance) {
        this.leftpowerbalance = leftpowerbalance;
    }

    public Double getPedalingindex() {
        return this.pedalingindex;
    }
    
    public void setPedalingindex(Double pedalingindex) {
        this.pedalingindex = pedalingindex;
    }
   








}
