package reger.dao;
// Generated Mar 7, 2006 3:43:02 PM by Hibernate Tools 3.1.0.beta4



/**
 * Savedsearcheventtype generated by hbm2java
 */

public class Savedsearcheventtype  implements java.io.Serializable {


    // Fields    

     private int savedsearcheventtypeid;
     private int savedsearchid;
     private int eventtypeid;


    // Constructors

    /** default constructor */
    public Savedsearcheventtype() {
    }

	/** minimal constructor */
    public Savedsearcheventtype(int savedsearcheventtypeid) {
        this.savedsearcheventtypeid = savedsearcheventtypeid;
    }
    
    /** full constructor */
    public Savedsearcheventtype(int savedsearcheventtypeid, Integer savedsearchid, Integer eventtypeid) {
        this.savedsearcheventtypeid = savedsearcheventtypeid;
        this.savedsearchid = savedsearchid;
        this.eventtypeid = eventtypeid;
    }
    

   
    // Property accessors

    public int getSavedsearcheventtypeid() {
        return this.savedsearcheventtypeid;
    }
    
    public void setSavedsearcheventtypeid(int savedsearcheventtypeid) {
        this.savedsearcheventtypeid = savedsearcheventtypeid;
    }

    public int getSavedsearchid() {
        return this.savedsearchid;
    }
    
    public void setSavedsearchid(int savedsearchid) {
        this.savedsearchid = savedsearchid;
    }

    public int getEventtypeid() {
        return this.eventtypeid;
    }
    
    public void setEventtypeid(int eventtypeid) {
        this.eventtypeid = eventtypeid;
    }
   








}
