package reger.dao;
// Generated Mar 7, 2006 3:43:00 PM by Hibernate Tools 3.1.0.beta4



/**
 * Savedsearchlog generated by hbm2java
 */

public class Savedsearchlog  implements java.io.Serializable {


    // Fields    

     private int savedsearchlogid;
     private int savedsearchid;
     private int logid;


    // Constructors

    /** default constructor */
    public Savedsearchlog() {
    }

	/** minimal constructor */
    public Savedsearchlog(int savedsearchlogid) {
        this.savedsearchlogid = savedsearchlogid;
    }
    
    /** full constructor */
    public Savedsearchlog(int savedsearchlogid, Integer savedsearchid, Integer logid) {
        this.savedsearchlogid = savedsearchlogid;
        this.savedsearchid = savedsearchid;
        this.logid = logid;
    }
    

   
    // Property accessors

    public int getSavedsearchlogid() {
        return this.savedsearchlogid;
    }
    
    public void setSavedsearchlogid(int savedsearchlogid) {
        this.savedsearchlogid = savedsearchlogid;
    }

    public int getSavedsearchid() {
        return this.savedsearchid;
    }
    
    public void setSavedsearchid(int savedsearchid) {
        this.savedsearchid = savedsearchid;
    }

    public int getLogid() {
        return this.logid;
    }
    
    public void setLogid(int logid) {
        this.logid = logid;
    }
   








}
