package reger.dao;
// Generated Mar 7, 2006 3:42:52 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * Systemmessage generated by hbm2java
 */

public class Systemmessage  implements java.io.Serializable {


    // Fields    

     private int systemmessageid;
     private String systemmessage;
     private boolean islive;
     private boolean autooldonrestart;
     private boolean showtologgedinusers;
     private boolean showtonotloggedinusers;
     private Date date;


    // Constructors

    /** default constructor */
    public Systemmessage() {
    }

	/** minimal constructor */
    public Systemmessage(int systemmessageid, Date date) {
        this.systemmessageid = systemmessageid;
        this.date = date;
    }
    
    /** full constructor */
    public Systemmessage(int systemmessageid, String systemmessage, boolean islive, boolean autooldonrestart, boolean showtologgedinusers, boolean showtonotloggedinusers, Date date) {
        this.systemmessageid = systemmessageid;
        this.systemmessage = systemmessage;
        this.islive = islive;
        this.autooldonrestart = autooldonrestart;
        this.showtologgedinusers = showtologgedinusers;
        this.showtonotloggedinusers = showtonotloggedinusers;
        this.date = date;
    }
    

   
    // Property accessors

    public int getSystemmessageid() {
        return this.systemmessageid;
    }
    
    public void setSystemmessageid(int systemmessageid) {
        this.systemmessageid = systemmessageid;
    }

    public String getSystemmessage() {
        return this.systemmessage;
    }
    
    public void setSystemmessage(String systemmessage) {
        this.systemmessage = systemmessage;
    }

    public boolean getIslive() {
        return this.islive;
    }
    
    public void setIslive(boolean islive) {
        this.islive = islive;
    }

    public boolean getAutooldonrestart() {
        return this.autooldonrestart;
    }
    
    public void setAutooldonrestart(boolean autooldonrestart) {
        this.autooldonrestart = autooldonrestart;
    }

    public boolean getShowtologgedinusers() {
        return this.showtologgedinusers;
    }
    
    public void setShowtologgedinusers(boolean showtologgedinusers) {
        this.showtologgedinusers = showtologgedinusers;
    }

    public boolean getShowtonotloggedinusers() {
        return this.showtonotloggedinusers;
    }
    
    public void setShowtonotloggedinusers(boolean showtonotloggedinusers) {
        this.showtonotloggedinusers = showtonotloggedinusers;
    }

    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
   








}
