package reger.dao;
// Generated Mar 7, 2006 3:43:18 PM by Hibernate Tools 3.1.0.beta4



/**
 * Systemlicense generated by hbm2java
 */

public class Systemlicense  implements java.io.Serializable {


    // Fields    

     private int systemlicenseid;
     private String encryptedlicense;


    // Constructors

    /** default constructor */
    public Systemlicense() {
    }

	/** minimal constructor */
    public Systemlicense(int systemlicenseid) {
        this.systemlicenseid = systemlicenseid;
    }
    
    /** full constructor */
    public Systemlicense(int systemlicenseid, String encryptedlicense) {
        this.systemlicenseid = systemlicenseid;
        this.encryptedlicense = encryptedlicense;
    }
    

   
    // Property accessors

    public int getSystemlicenseid() {
        return this.systemlicenseid;
    }
    
    public void setSystemlicenseid(int systemlicenseid) {
        this.systemlicenseid = systemlicenseid;
    }

    public String getEncryptedlicense() {
        return this.encryptedlicense;
    }
    
    public void setEncryptedlicense(String encryptedlicense) {
        this.encryptedlicense = encryptedlicense;
    }
   








}
