package reger.dao;
// Generated Mar 7, 2006 3:42:56 PM by Hibernate Tools 3.1.0.beta4



/**
 * Tag generated by hbm2java
 */

public class Tag  implements java.io.Serializable {


    // Fields    

     private int tagid;
     private String tag;


    // Constructors

    /** default constructor */
    public Tag() {
    }

    
    /** full constructor */
    public Tag(int tagid, String tag) {
        this.tagid = tagid;
        this.tag = tag;
    }
    

   
    // Property accessors

    public int getTagid() {
        return this.tagid;
    }
    
    public void setTagid(int tagid) {
        this.tagid = tagid;
    }

    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }
   








}
