package reger.dao;
// Generated Mar 7, 2006 3:42:50 PM by Hibernate Tools 3.1.0.beta4



/**
 * Templatenew generated by hbm2java
 */

public class Templatenew  implements java.io.Serializable {


    // Fields    

     private int templateid;
     private String template;
     private int type;
     private int accountid;
     private boolean issystemtemplate;
     private String name;


    // Constructors

    /** default constructor */
    public Templatenew() {
    }

	/** minimal constructor */
    public Templatenew(int templateid, int type, String name) {
        this.templateid = templateid;
        this.type = type;
        this.name = name;
    }
    
    /** full constructor */
    public Templatenew(int templateid, String template, int type, Integer accountid, boolean issystemtemplate, String name) {
        this.templateid = templateid;
        this.template = template;
        this.type = type;
        this.accountid = accountid;
        this.issystemtemplate = issystemtemplate;
        this.name = name;
    }
    

   
    // Property accessors

    public int getTemplateid() {
        return this.templateid;
    }
    
    public void setTemplateid(int templateid) {
        this.templateid = templateid;
    }

    public String getTemplate() {
        return this.template;
    }
    
    public void setTemplate(String template) {
        this.template = template;
    }

    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }

    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }

    public boolean getIssystemtemplate() {
        return this.issystemtemplate;
    }
    
    public void setIssystemtemplate(boolean issystemtemplate) {
        this.issystemtemplate = issystemtemplate;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
   








}
