package reger.dao;
// Generated Mar 7, 2006 3:42:53 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * Traffic generated by hbm2java
 */

public class Traffic  implements java.io.Serializable {


    // Fields    

     private int trafficid;
     private int count;
     private int traffictypeid;
     private Date datetime;
     private String url;
     private int plid;
     private int accountid;
     private int logid;
     private int eventid;
     private int imageid;
     private String referrer;
     private String browser;
     private String remotehost;
     private boolean iscollapsed;


    // Constructors

    /** default constructor */
    public Traffic() {
    }

	/** minimal constructor */
    public Traffic(int trafficid) {
        this.trafficid = trafficid;
    }
    
    /** full constructor */
    public Traffic(int trafficid, Integer count, Integer traffictypeid, Date datetime, String url, Integer plid, Integer accountid, Integer logid, Integer eventid, Integer imageid, String referrer, String browser, String remotehost, boolean iscollapsed) {
        this.trafficid = trafficid;
        this.count = count;
        this.traffictypeid = traffictypeid;
        this.datetime = datetime;
        this.url = url;
        this.plid = plid;
        this.accountid = accountid;
        this.logid = logid;
        this.eventid = eventid;
        this.imageid = imageid;
        this.referrer = referrer;
        this.browser = browser;
        this.remotehost = remotehost;
        this.iscollapsed = iscollapsed;
    }
    

   
    // Property accessors

    public int getTrafficid() {
        return this.trafficid;
    }
    
    public void setTrafficid(int trafficid) {
        this.trafficid = trafficid;
    }

    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }

    public int getTraffictypeid() {
        return this.traffictypeid;
    }
    
    public void setTraffictypeid(int traffictypeid) {
        this.traffictypeid = traffictypeid;
    }

    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    public int getPlid() {
        return this.plid;
    }
    
    public void setPlid(int plid) {
        this.plid = plid;
    }

    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }

    public int getLogid() {
        return this.logid;
    }
    
    public void setLogid(int logid) {
        this.logid = logid;
    }

    public int getEventid() {
        return this.eventid;
    }
    
    public void setEventid(int eventid) {
        this.eventid = eventid;
    }

    public int getImageid() {
        return this.imageid;
    }
    
    public void setImageid(int imageid) {
        this.imageid = imageid;
    }

    public String getReferrer() {
        return this.referrer;
    }
    
    public void setReferrer(String referrer) {
        this.referrer = referrer;
    }

    public String getBrowser() {
        return this.browser;
    }
    
    public void setBrowser(String browser) {
        this.browser = browser;
    }

    public String getRemotehost() {
        return this.remotehost;
    }
    
    public void setRemotehost(String remotehost) {
        this.remotehost = remotehost;
    }

    public boolean getIscollapsed() {
        return this.iscollapsed;
    }
    
    public void setIscollapsed(boolean iscollapsed) {
        this.iscollapsed = iscollapsed;
    }
   








}
